"""Narrow boundaries implemented by simulated and physical local controls."""

from __future__ import annotations

from collections.abc import Callable
from typing import Protocol

from e87canbus.local_controls.model import LocalControlsEvent, PanelDisplayState

LocalControlsInputSink = Callable[[LocalControlsEvent], bool]


class Clock(Protocol):
    def __call__(self) -> float: ...


class PanelPort(Protocol):
    def start(self, submit: LocalControlsInputSink) -> None: ...
    def set_display(self, display: PanelDisplayState) -> None: ...
    def poll(self, now: float) -> None: ...
    def close(self) -> None: ...


class HotspotPort(Protocol):
    def start(self, submit: LocalControlsInputSink) -> None: ...
    def activate(self) -> None: ...
    def deactivate(self) -> None: ...
    def poll(self, now: float) -> None: ...
    def close(self) -> None: ...


class CoordinatorConditionPort(Protocol):
    """The complete, one-way contract from controller composition to local controls."""

    def start(self, submit: LocalControlsInputSink) -> None: ...
    def poll(self, now: float) -> None: ...
    def close(self) -> None: ...
