[platformio]
default_envs = qtpy_rp2040

[env:qtpy_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#9c167c6b8aac4f4cfa6d55a0c4e5b848795150c0
board = adafruit_qtpy
framework = arduino
lib_deps =
    adafruit/Adafruit NeoPixel @ 1.15.5

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter =
    +<panel_logic.cpp>
    -<main.cpp>
