[env:qtpy_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_qtpy
framework = arduino
upload_protocol = picotool
lib_deps = adafruit/Adafruit NeoPixel

[env:native]
platform = native
test_framework = unity
build_src_filter = -<*>
test_build_src = yes
