// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  ServerSentEventsResult,
  TDataShape,
} from "./client"
import { client } from "./client.gen"
import type {
  LivenessHealthLiveGetData,
  LivenessHealthLiveGetResponses,
  ReadinessHealthReadyGetData,
  ReadinessHealthReadyGetResponses,
  StreamConsoleLiveApiLiveGetData,
  StreamConsoleLiveApiLiveGetResponse,
  StreamConsoleLiveApiLiveGetResponses,
} from "./types.gen"
import {
  zLivenessHealthLiveGetResponse,
  zStreamConsoleLiveApiLiveGetResponse,
} from "./zod.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Stream Console Live
 */
export const streamConsoleLiveApiLiveGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    StreamConsoleLiveApiLiveGetData,
    ThrowOnError,
    StreamConsoleLiveApiLiveGetResponse
  >
): Promise<ServerSentEventsResult<StreamConsoleLiveApiLiveGetResponses>> =>
  (options?.client ?? client).sse.get<
    StreamConsoleLiveApiLiveGetResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zStreamConsoleLiveApiLiveGetResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/live",
    ...options,
  })

/**
 * Liveness
 */
export const livenessHealthLiveGet = <ThrowOnError extends boolean = false>(
  options?: Options<LivenessHealthLiveGetData, ThrowOnError>
): RequestResult<
  LivenessHealthLiveGetResponses,
  unknown,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    LivenessHealthLiveGetResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zLivenessHealthLiveGetResponse.parseAsync(data),
    responseStyle: "data",
    url: "/health/live",
    ...options,
  })

/**
 * Readiness
 */
export const readinessHealthReadyGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadinessHealthReadyGetData, ThrowOnError>
): RequestResult<
  ReadinessHealthReadyGetResponses,
  unknown,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    ReadinessHealthReadyGetResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/health/ready",
    ...options,
  })
