// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

/**
 * ConsoleCanState
 */
export type ConsoleCanState = {
  /**
   * Connected
   */
  connected: boolean
  /**
   * Fault
   */
  fault: string | null
  /**
   * Frames Received
   */
  frames_received: number
  /**
   * Interface
   */
  interface?: "kcan"
}

/**
 * ConsoleSnapshotData
 */
export type ConsoleSnapshotData = {
  can: ConsoleCanState
}

/**
 * ConsoleSnapshotEvent
 *
 * Complete local state sent by the console host's SSE endpoint.
 */
export type ConsoleSnapshotEvent = {
  data: ConsoleSnapshotData
  /**
   * Type
   */
  type: "console.snapshot"
}

export type StreamConsoleLiveApiLiveGetData = {
  body?: never
  path?: never
  query?: never
  url: "/api/live"
}

export type StreamConsoleLiveApiLiveGetResponses = {
  /**
   * Successful Response
   */
  200: ConsoleSnapshotEvent
}

export type StreamConsoleLiveApiLiveGetResponse =
  StreamConsoleLiveApiLiveGetResponses[keyof StreamConsoleLiveApiLiveGetResponses]

export type LivenessHealthLiveGetData = {
  body?: never
  path?: never
  query?: never
  url: "/health/live"
}

export type LivenessHealthLiveGetResponses = {
  /**
   * Response Liveness Health Live Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type LivenessHealthLiveGetResponse =
  LivenessHealthLiveGetResponses[keyof LivenessHealthLiveGetResponses]

export type ReadinessHealthReadyGetData = {
  body?: never
  path?: never
  query?: never
  url: "/health/ready"
}

export type ReadinessHealthReadyGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}
