// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod"

/**
 * ConsoleCanState
 */
export const zConsoleCanState = z.object({
  connected: z.boolean(),
  fault: z.string().nullable(),
  frames_received: z.int().gte(0),
  interface: z.literal("kcan").optional().default("kcan"),
})

/**
 * ConsoleSnapshotData
 */
export const zConsoleSnapshotData = z.object({
  can: zConsoleCanState,
})

/**
 * ConsoleSnapshotEvent
 *
 * Complete local state sent by the console host's SSE endpoint.
 */
export const zConsoleSnapshotEvent = z.object({
  data: zConsoleSnapshotData,
  type: z.literal("console.snapshot"),
})

/**
 * Successful Response
 */
export const zStreamConsoleLiveApiLiveGetResponse = zConsoleSnapshotEvent

/**
 * Response Liveness Health Live Get
 *
 * Successful Response
 */
export const zLivenessHealthLiveGetResponse = z.record(z.string(), z.string())
