[env:micro]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino
lib_deps =
    EEPROM
    symlink://../../embedded-libs/isotp_transport
    https://github.com/SimonCahill/isotp-c.git#b2fb084aadfed6e36a97a3e67282d2777fdad0d3
    https://github.com/coryjfowler/MCP_CAN_lib.git
build_flags =
    -D CAN_CS_PIN=10
    -D MCP2515_CLOCK=MCP_8MHZ
    -D PWM_OUTPUT_PIN=9
    -D PWM_DUTY_CEILING=180

[env:native]
platform = native
test_framework = unity
build_src_filter = -<*>
test_build_src = yes
