// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod"

/**
 * ActivateSteeringProfileRequest
 */
export const zActivateSteeringProfileRequest = z.object({
  expected_revision: z.int().gte(1),
  profile_id: z
    .string()
    .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/),
})

/**
 * AdjustManualAssistanceCommand
 */
export const zAdjustManualAssistanceCommand = z.object({
  delta: z.union([z.literal(-1), z.literal(1)]),
  type: z.literal("adjust_manual_assistance"),
})

/**
 * AdjustManualAssistanceRequest
 */
export const zAdjustManualAssistanceRequest = z.object({
  delta: z.union([z.literal(-1), z.literal(1)]),
})

/**
 * BlinkAnimationRequest
 */
export const zBlinkAnimationRequest = z.object({
  kind: z.literal("blink"),
  off_ms: z.int().gte(1).lte(10000),
  on_ms: z.int().gte(1).lte(10000),
})

/**
 * BreatheAnimationRequest
 *
 * Bounds mirror the button-pad track payload, so an accepted animation is runnable.
 */
export const zBreatheAnimationRequest = z.object({
  kind: z.literal("breathe"),
  maximum: z.int().gte(0).lte(255),
  minimum: z.int().gte(0).lte(255),
  period_ms: z.int().gte(250).lte(10000),
})

/**
 * CommandAcknowledgement
 */
export const zCommandAcknowledgement = z.object({
  accepted: z.literal(true).optional().default(true),
  boot_id: z.string(),
  revision: z.int().gte(1),
})

/**
 * CoordinatorStatus
 */
export const zCoordinatorStatus = z.enum(["starting", "ready", "fault", "off"])

/**
 * DeploymentProfile
 */
export const zDeploymentProfile = z.enum(["car", "bench", "simulator"])

/**
 * DeviceRole
 */
export const zDeviceRole = z.enum(["button_pad", "servotronic_controller"])

/**
 * EngineRpmRequest
 */
export const zEngineRpmRequest = z.object({
  rpm: z.int().gte(0).lte(12000),
})

/**
 * HotspotStatus
 */
export const zHotspotStatus = z.enum([
  "disabled",
  "starting",
  "waiting",
  "connected",
  "stopping",
  "failed",
])

/**
 * LivenessResponse
 */
export const zLivenessResponse = z.object({
  status: z.literal("live").optional().default("live"),
})

/**
 * PanelDisplay
 */
export const zPanelDisplay = z.enum([
  "starting",
  "ready",
  "hotspot_waiting",
  "hotspot_connected",
  "fault",
  "off",
])

/**
 * ReadinessResponse
 */
export const zReadinessResponse = z.object({
  boot_id: z.string().min(1),
  status: z.enum(["ready", "not_ready"]),
})

/**
 * RuntimeCapabilities
 */
export const zRuntimeCapabilities = z.object({
  simulated_vehicle: z.boolean(),
  simulation_workbench: z.boolean(),
})

/**
 * RuntimeConfigurationResponse
 */
export const zRuntimeConfigurationResponse = z.object({
  capabilities: zRuntimeCapabilities,
  profile: zDeploymentProfile,
})

/**
 * SelectSteeringModeCommand
 */
export const zSelectSteeringModeCommand = z.object({
  mode: z.enum(["auto", "manual"]),
  type: z.literal("select_steering_mode"),
})

/**
 * SetManualAssistanceLevelCommand
 */
export const zSetManualAssistanceLevelCommand = z.object({
  level: z.int().gte(0),
  type: z.literal("set_manual_assistance_level"),
})

/**
 * SetManualAssistanceLevelRequest
 */
export const zSetManualAssistanceLevelRequest = z.object({
  level: z.int().gte(0),
})

/**
 * SetMaximumAssistanceCommand
 */
export const zSetMaximumAssistanceCommand = z.object({
  enabled: z.boolean(),
  type: z.literal("set_maximum_assistance"),
})

/**
 * SetMaximumAssistanceRequest
 */
export const zSetMaximumAssistanceRequest = z.object({
  enabled: z.boolean(),
})

/**
 * SetSteeringModeRequest
 */
export const zSetSteeringModeRequest = z.object({
  mode: z.enum(["auto", "manual"]),
})

/**
 * SimulationCommandAcknowledgement
 */
export const zSimulationCommandAcknowledgement = z.object({
  accepted: z.literal(true).optional().default(true),
  boot_id: z.string(),
})

/**
 * SimulationCoordinatorPanelState
 */
export const zSimulationCoordinatorPanelState = z.object({
  coordinator_status: zCoordinatorStatus,
  coordinator_status_preview: zCoordinatorStatus.nullable(),
  display: zPanelDisplay,
  failure_armed: z.boolean(),
  hotspot_status: zHotspotStatus,
})

/**
 * SimulationCoordinatorStatusRequest
 */
export const zSimulationCoordinatorStatusRequest = z.object({
  status: z.enum(["starting", "ready", "fault", "off"]).nullable(),
})

/**
 * SimulationDeviceProtocolVersionRequest
 */
export const zSimulationDeviceProtocolVersionRequest = z.object({
  protocol_version: z.int().gte(0).lte(255),
})

/**
 * SimulationDeviceStatusCodeRequest
 */
export const zSimulationDeviceStatusCodeRequest = z.object({
  status_code: z.int().gte(0).lte(255),
})

/**
 * SpeedRequest
 */
export const zSpeedRequest = z.object({
  speed_kph: z.number().gte(0).lte(300),
})

/**
 * SpeedUnit
 */
export const zSpeedUnit = z.enum(["mph", "kmh"])

/**
 * StartHighBeamStrobeCommand
 */
export const zStartHighBeamStrobeCommand = z.object({
  type: z.literal("start_high_beam_strobe"),
})

/**
 * SteeringCurvePointRequest
 */
export const zSteeringCurvePointRequest = z.object({
  assistance_per_mille: z.int().gte(0).lte(1000),
  speed_deci_kph: z.int().gte(0),
})

/**
 * SteeringCurveDefinitionRequest
 */
export const zSteeringCurveDefinitionRequest = z.object({
  points: z.tuple([
    zSteeringCurvePointRequest,
    zSteeringCurvePointRequest,
    zSteeringCurvePointRequest,
    zSteeringCurvePointRequest,
    zSteeringCurvePointRequest,
    zSteeringCurvePointRequest,
    zSteeringCurvePointRequest,
    zSteeringCurvePointRequest,
  ]),
  schema_version: z.literal(1),
})

/**
 * ActivateSteeringCurveRequest
 */
export const zActivateSteeringCurveRequest = z.object({
  definition: zSteeringCurveDefinitionRequest,
})

/**
 * CreateProfileRequest
 */
export const zCreateProfileRequest = z.object({
  definition: zSteeringCurveDefinitionRequest,
  name: z.string().min(1).max(100),
})

/**
 * SteeringCurvePointResponse
 */
export const zSteeringCurvePointResponse = z.object({
  assistance_per_mille: z.int().gte(0).lte(1000),
  speed_deci_kph: z.int().gte(0),
})

/**
 * SteeringCurveDefinitionResponse
 */
export const zSteeringCurveDefinitionResponse = z.object({
  points: z.tuple([
    zSteeringCurvePointResponse,
    zSteeringCurvePointResponse,
    zSteeringCurvePointResponse,
    zSteeringCurvePointResponse,
    zSteeringCurvePointResponse,
    zSteeringCurvePointResponse,
    zSteeringCurvePointResponse,
    zSteeringCurvePointResponse,
  ]),
  schema_version: z.literal(1),
})

/**
 * SteeringProfileResponse
 */
export const zSteeringProfileResponse = z.object({
  created_at: z.string(),
  definition: zSteeringCurveDefinitionResponse,
  name: z.string().min(1).max(100),
  profile_id: z
    .string()
    .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/),
  revision: z.int().gte(1),
  updated_at: z.string(),
})

/**
 * TemperatureRequest
 */
export const zTemperatureRequest = z.object({
  temperature_c: z.number().gte(-40).lte(250),
})

/**
 * TemperatureUnit
 */
export const zTemperatureUnit = z.enum(["c", "f"])

/**
 * ApplicationSettingsResponse
 */
export const zApplicationSettingsResponse = z.object({
  coolant_critical_c: z.number(),
  coolant_operating_c: z.number(),
  coolant_warning_c: z.number(),
  dashboard_id: z
    .string()
    .min(1)
    .max(64)
    .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  oil_critical_c: z.number(),
  oil_operating_c: z.number(),
  oil_warning_c: z.number(),
  redline_rpm: z.int(),
  revision: z.int().gte(1),
  shift_stage_1_rpm: z.int(),
  shift_stage_2_rpm: z.int(),
  speed_unit: zSpeedUnit,
  temperature_unit: zTemperatureUnit,
  updated_at: z.string(),
})

/**
 * ToggleAutomaticAssistanceCommand
 */
export const zToggleAutomaticAssistanceCommand = z.object({
  type: z.literal("toggle_automatic_assistance"),
})

/**
 * ToggleMaximumAssistanceCommand
 */
export const zToggleMaximumAssistanceCommand = z.object({
  type: z.literal("toggle_maximum_assistance"),
})

/**
 * ButtonProfileSlotRequest
 *
 * One authored button: presentation is a sibling of the command, not part of it.
 *
 * ``active_colour`` is reserved and typed as null so a client cannot start depending on
 * a second colour before the renderer honours one. Whether an animation is permitted at
 * all depends on the bound command having an observable condition, which the domain
 * decides at the save boundary.
 */
export const zButtonProfileSlotRequest = z.object({
  active_colour: z.null().optional(),
  animation: z
    .discriminatedUnion("kind", [
      zBreatheAnimationRequest,
      zBlinkAnimationRequest,
    ])
    .nullish(),
  colour: z.tuple([
    z.int().gte(0).lte(255),
    z.int().gte(0).lte(255),
    z.int().gte(0).lte(255),
  ]),
  command: z.discriminatedUnion("type", [
    zSelectSteeringModeCommand,
    zToggleAutomaticAssistanceCommand,
    zAdjustManualAssistanceCommand,
    zSetManualAssistanceLevelCommand,
    zSetMaximumAssistanceCommand,
    zToggleMaximumAssistanceCommand,
    zStartHighBeamStrobeCommand,
  ]),
})

/**
 * ButtonProfileDefinitionRequest
 */
export const zButtonProfileDefinitionRequest = z.object({
  slots: z.tuple([
    zButtonProfileSlotRequest.nullable(),
    zButtonProfileSlotRequest.nullable(),
    zButtonProfileSlotRequest.nullable(),
    zButtonProfileSlotRequest.nullable(),
    zButtonProfileSlotRequest.nullable(),
    zButtonProfileSlotRequest.nullable(),
    zButtonProfileSlotRequest.nullable(),
    zButtonProfileSlotRequest.nullable(),
    zButtonProfileSlotRequest.nullable(),
    zButtonProfileSlotRequest.nullable(),
    zButtonProfileSlotRequest.nullable(),
    zButtonProfileSlotRequest.nullable(),
    zButtonProfileSlotRequest.nullable(),
    zButtonProfileSlotRequest.nullable(),
    zButtonProfileSlotRequest.nullable(),
    zButtonProfileSlotRequest.nullable(),
  ]),
})

/**
 * ButtonProfileSlotResponse
 */
export const zButtonProfileSlotResponse = z.object({
  active_colour: z.null(),
  animation: z
    .discriminatedUnion("kind", [
      zBreatheAnimationRequest,
      zBlinkAnimationRequest,
    ])
    .nullable(),
  colour: z.tuple([
    z.int().gte(0).lte(255),
    z.int().gte(0).lte(255),
    z.int().gte(0).lte(255),
  ]),
  command: z.discriminatedUnion("type", [
    zSelectSteeringModeCommand,
    zToggleAutomaticAssistanceCommand,
    zAdjustManualAssistanceCommand,
    zSetManualAssistanceLevelCommand,
    zSetMaximumAssistanceCommand,
    zToggleMaximumAssistanceCommand,
    zStartHighBeamStrobeCommand,
  ]),
})

/**
 * ButtonProfileDefinitionResponse
 */
export const zButtonProfileDefinitionResponse = z.object({
  slots: z.tuple([
    zButtonProfileSlotResponse.nullable(),
    zButtonProfileSlotResponse.nullable(),
    zButtonProfileSlotResponse.nullable(),
    zButtonProfileSlotResponse.nullable(),
    zButtonProfileSlotResponse.nullable(),
    zButtonProfileSlotResponse.nullable(),
    zButtonProfileSlotResponse.nullable(),
    zButtonProfileSlotResponse.nullable(),
    zButtonProfileSlotResponse.nullable(),
    zButtonProfileSlotResponse.nullable(),
    zButtonProfileSlotResponse.nullable(),
    zButtonProfileSlotResponse.nullable(),
    zButtonProfileSlotResponse.nullable(),
    zButtonProfileSlotResponse.nullable(),
    zButtonProfileSlotResponse.nullable(),
    zButtonProfileSlotResponse.nullable(),
  ]),
})

/**
 * ButtonProfileResponse
 */
export const zButtonProfileResponse = z.object({
  created_at: z.string(),
  definition: zButtonProfileDefinitionResponse,
  name: z.string().min(1).max(100),
  profile_id: z
    .string()
    .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/),
  revision: z.int().gte(1),
  updated_at: z.string(),
})

/**
 * CreateButtonProfileRequest
 */
export const zCreateButtonProfileRequest = z.object({
  definition: zButtonProfileDefinitionRequest.nullish(),
  name: z.string().min(1).max(100),
})

/**
 * UpdateApplicationSettingsRequest
 */
export const zUpdateApplicationSettingsRequest = z.object({
  coolant_critical_c: z.number().gte(-40).lte(250),
  coolant_operating_c: z.number().gte(-40).lte(250),
  coolant_warning_c: z.number().gte(-40).lte(250),
  dashboard_id: z
    .string()
    .min(1)
    .max(64)
    .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  expected_revision: z.int().gte(1),
  oil_critical_c: z.number().gte(-40).lte(250),
  oil_operating_c: z.number().gte(-40).lte(250),
  oil_warning_c: z.number().gte(-40).lte(250),
  redline_rpm: z.int().gte(1000).lte(12000),
  shift_stage_1_rpm: z.int().gte(1000).lte(12000),
  shift_stage_2_rpm: z.int().gte(1000).lte(12000),
  speed_unit: z.enum(["mph", "kmh"]),
  temperature_unit: z.enum(["c", "f"]),
})

/**
 * UpdateButtonProfileRequest
 */
export const zUpdateButtonProfileRequest = z.object({
  definition: zButtonProfileDefinitionRequest,
  expected_revision: z.int().gte(1),
  name: z.string().min(1).max(100),
})

/**
 * UpdateProfileRequest
 */
export const zUpdateProfileRequest = z.object({
  definition: zSteeringCurveDefinitionRequest,
  expected_revision: z.int().gte(1),
  name: z.string().min(1).max(100),
})

/**
 * ValidationError
 */
export const zValidationError = z.object({
  ctx: z.record(z.string(), z.unknown()).optional(),
  input: z.unknown().optional(),
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
})

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
})

/**
 * ValidationIssue
 */
export const zValidationIssue = z.object({
  location: z.array(z.union([z.string(), z.int()])),
  message: z.string(),
  type: z.string(),
})

/**
 * ApiProblemDetail
 */
export const zApiProblemDetail = z.object({
  code: z.enum([
    "validation_error",
    "settings_revision_conflict",
    "settings_storage_error",
    "profile_not_found",
    "profile_revision_conflict",
    "profile_name_conflict",
    "profile_storage_error",
    "profile_protected",
    "runtime_queue_full",
    "controller_unavailable",
    "command_timeout",
    "simulation_device_unavailable",
    "controller_failed",
    "feature_unavailable",
    "controller_runtime_error",
  ]),
  current_revision: z.int().nullish(),
  issues: z.array(zValidationIssue).nullish(),
  message: z.string(),
})

/**
 * ApiProblemResponse
 */
export const zApiProblemResponse = z.object({
  error: zApiProblemDetail,
})

/**
 * VehicleSweepRequest
 */
export const zVehicleSweepRequest = z.object({
  enabled: z.boolean(),
})

/**
 * Successful Response
 */
export const zGetSavedButtonProfileResponse = zButtonProfileResponse

/**
 * Response Listbuttonprofiles
 *
 * Successful Response
 */
export const zListButtonProfilesResponse = z.array(zButtonProfileResponse)

export const zCreateButtonProfileBody = zCreateButtonProfileRequest

/**
 * Successful Response
 */
export const zCreateButtonProfileResponse = zButtonProfileResponse

export const zDeleteButtonProfilePath = z.object({
  profile_id: z
    .string()
    .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/),
})

export const zDeleteButtonProfileQuery = z.object({
  expected_revision: z.int().gte(1),
})

/**
 * Successful Response
 */
export const zDeleteButtonProfileResponse = z.void()

export const zGetButtonProfilePath = z.object({
  profile_id: z
    .string()
    .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/),
})

/**
 * Successful Response
 */
export const zGetButtonProfileResponse = zButtonProfileResponse

export const zUpdateButtonProfileBody = zUpdateButtonProfileRequest

export const zUpdateButtonProfilePath = z.object({
  profile_id: z
    .string()
    .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/),
})

/**
 * Successful Response
 */
export const zUpdateButtonProfileResponse = zButtonProfileResponse

/**
 * Successful Response
 */
export const zGetSimulationCoordinatorPanelResponse =
  zSimulationCoordinatorPanelState

/**
 * Successful Response
 */
export const zPressSimulationCoordinatorPanelButtonResponse =
  zSimulationCoordinatorPanelState

/**
 * Successful Response
 */
export const zConnectSimulationHotspotClientResponse =
  zSimulationCoordinatorPanelState

/**
 * Successful Response
 */
export const zDisconnectSimulationHotspotClientResponse =
  zSimulationCoordinatorPanelState

export const zPreviewSimulationCoordinatorStatusBody =
  zSimulationCoordinatorStatusRequest

/**
 * Successful Response
 */
export const zPreviewSimulationCoordinatorStatusResponse =
  zSimulationCoordinatorPanelState

/**
 * Successful Response
 */
export const zFailNextSimulationHotspotOperationResponse =
  zSimulationCoordinatorPanelState

export const zTapSimulationButtonPath = z.object({
  button_index: z.int().gte(0).lt(16),
})

/**
 * Successful Response
 */
export const zTapSimulationButtonResponse = zSimulationCommandAcknowledgement

export const zConnectSimulationDevicePath = z.object({
  role: zDeviceRole,
})

/**
 * Successful Response
 */
export const zConnectSimulationDeviceResponse =
  zSimulationCommandAcknowledgement

export const zDisconnectSimulationDevicePath = z.object({
  role: zDeviceRole,
})

/**
 * Successful Response
 */
export const zDisconnectSimulationDeviceResponse =
  zSimulationCommandAcknowledgement

export const zSetSimulationDeviceProtocolVersionBody =
  zSimulationDeviceProtocolVersionRequest

export const zSetSimulationDeviceProtocolVersionPath = z.object({
  role: zDeviceRole,
})

/**
 * Successful Response
 */
export const zSetSimulationDeviceProtocolVersionResponse =
  zSimulationCommandAcknowledgement

export const zRebootSimulationDevicePath = z.object({
  role: zDeviceRole,
})

/**
 * Successful Response
 */
export const zRebootSimulationDeviceResponse = zSimulationCommandAcknowledgement

export const zSetSimulationDeviceStatusCodeBody =
  zSimulationDeviceStatusCodeRequest

export const zSetSimulationDeviceStatusCodePath = z.object({
  role: zDeviceRole,
})

/**
 * Successful Response
 */
export const zSetSimulationDeviceStatusCodeResponse =
  zSimulationCommandAcknowledgement

/**
 * Successful Response
 */
export const zResetSimulationResponse = zSimulationCommandAcknowledgement

export const zSetCoolantTemperatureBody = zTemperatureRequest

/**
 * Successful Response
 */
export const zSetCoolantTemperatureResponse = zSimulationCommandAcknowledgement

/**
 * Successful Response
 */
export const zSilenceCoolantTemperatureResponse =
  zSimulationCommandAcknowledgement

export const zSetOilTemperatureBody = zTemperatureRequest

/**
 * Successful Response
 */
export const zSetOilTemperatureResponse = zSimulationCommandAcknowledgement

/**
 * Successful Response
 */
export const zSilenceOilTemperatureResponse = zSimulationCommandAcknowledgement

export const zSetEngineRpmBody = zEngineRpmRequest

/**
 * Successful Response
 */
export const zSetEngineRpmResponse = zSimulationCommandAcknowledgement

/**
 * Successful Response
 */
export const zSilenceEngineRpmResponse = zSimulationCommandAcknowledgement

export const zSetVehicleSpeedBody = zSpeedRequest

/**
 * Successful Response
 */
export const zSetVehicleSpeedResponse = zSimulationCommandAcknowledgement

/**
 * Successful Response
 */
export const zSilenceVehicleSpeedResponse = zSimulationCommandAcknowledgement

export const zSetVehicleSweepBody = zVehicleSweepRequest

/**
 * Successful Response
 */
export const zSetVehicleSweepResponse = zSimulationCommandAcknowledgement

/**
 * Successful Response
 */
export const zGetRuntimeConfigurationResponse = zRuntimeConfigurationResponse

/**
 * Successful Response
 */
export const zGetApplicationSettingsResponse = zApplicationSettingsResponse

export const zUpdateApplicationSettingsBody = zUpdateApplicationSettingsRequest

/**
 * Successful Response
 */
export const zUpdateApplicationSettingsResponse = zApplicationSettingsResponse

export const zActivateSteeringProfileBody = zActivateSteeringProfileRequest

/**
 * Successful Response
 */
export const zActivateSteeringProfileResponse = zCommandAcknowledgement

export const zActivateSteeringCurveBody = zActivateSteeringCurveRequest

/**
 * Successful Response
 */
export const zActivateSteeringCurveResponse = zCommandAcknowledgement

export const zAdjustManualAssistanceBody = zAdjustManualAssistanceRequest

/**
 * Successful Response
 */
export const zAdjustManualAssistanceResponse = zCommandAcknowledgement

export const zSetManualAssistanceLevelBody = zSetManualAssistanceLevelRequest

/**
 * Successful Response
 */
export const zSetManualAssistanceLevelResponse = zCommandAcknowledgement

export const zSetMaximumAssistanceBody = zSetMaximumAssistanceRequest

/**
 * Successful Response
 */
export const zSetMaximumAssistanceResponse = zCommandAcknowledgement

export const zSetSteeringModeBody = zSetSteeringModeRequest

/**
 * Successful Response
 */
export const zSetSteeringModeResponse = zCommandAcknowledgement

/**
 * Successful Response
 */
export const zGetSavedSteeringProfileResponse = zSteeringProfileResponse

/**
 * Response Liststeeringprofiles
 *
 * Successful Response
 */
export const zListSteeringProfilesResponse = z.array(zSteeringProfileResponse)

export const zCreateSteeringProfileBody = zCreateProfileRequest

/**
 * Successful Response
 */
export const zCreateSteeringProfileResponse = zSteeringProfileResponse

export const zDeleteSteeringProfilePath = z.object({
  profile_id: z
    .string()
    .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/),
})

export const zDeleteSteeringProfileQuery = z.object({
  expected_revision: z.int().gte(1),
})

/**
 * Successful Response
 */
export const zDeleteSteeringProfileResponse = z.void()

export const zGetSteeringProfilePath = z.object({
  profile_id: z
    .string()
    .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/),
})

/**
 * Successful Response
 */
export const zGetSteeringProfileResponse = zSteeringProfileResponse

export const zUpdateSteeringProfileBody = zUpdateProfileRequest

export const zUpdateSteeringProfilePath = z.object({
  profile_id: z
    .string()
    .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/),
})

/**
 * Successful Response
 */
export const zUpdateSteeringProfileResponse = zSteeringProfileResponse

/**
 * Successful Response
 */
export const zCheckLivenessResponse = zLivenessResponse

/**
 * Successful Response
 */
export const zCheckReadinessResponse = zReadinessResponse
