table inet e87canbus {
    chain input {
        type filter hook input priority filter; policy accept;
        iifname "wlan0" ct state established,related accept
        iifname "wlan0" udp dport 67 accept
        iifname "wlan0" tcp dport { 22, 443 } accept
        iifname "wlan0" ip protocol icmp accept
        iifname "wlan0" drop
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
    }
}
