export {
  Abs,
  Battery,
  CheckEngine,
  CoolantTemperature,
  Fuel,
  HighBeam,
  LowBeam,
  OilPressure,
  TirePressure,
  TractionControl,
  TurnSignalLeft,
  TurnSignalRight,
  type DashboardIconProps,
} from "./dashboard-icons"
