// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query"

import { client } from "../client.gen"
import {
  activateSteeringCurve,
  activateSteeringProfile,
  adjustManualAssistance,
  checkLiveness,
  checkReadiness,
  connectSimulationDevice,
  connectSimulationHotspotClient,
  createButtonProfile,
  createSteeringProfile,
  deleteButtonProfile,
  deleteSteeringProfile,
  disconnectSimulationDevice,
  disconnectSimulationHotspotClient,
  failNextSimulationHotspotOperation,
  getApplicationSettings,
  getButtonProfile,
  getRuntimeConfiguration,
  getSavedButtonProfile,
  getSavedSteeringProfile,
  getSimulationCoordinatorPanel,
  getSteeringProfile,
  listButtonProfiles,
  listSteeringProfiles,
  type Options,
  pressSimulationCoordinatorPanelButton,
  previewSimulationCoordinatorStatus,
  rebootSimulationDevice,
  resetSimulation,
  setCoolantTemperature,
  setEngineRpm,
  setManualAssistanceLevel,
  setMaximumAssistance,
  setOilTemperature,
  setSimulationDeviceProtocolVersion,
  setSimulationDeviceStatusCode,
  setSteeringMode,
  setVehicleSpeed,
  setVehicleSweep,
  silenceCoolantTemperature,
  silenceEngineRpm,
  silenceOilTemperature,
  silenceVehicleSpeed,
  tapSimulationButton,
  updateApplicationSettings,
  updateButtonProfile,
  updateSteeringProfile,
} from "../sdk.gen"
import type {
  ActivateSteeringCurveData,
  ActivateSteeringCurveError,
  ActivateSteeringCurveResponse,
  ActivateSteeringProfileData,
  ActivateSteeringProfileError,
  ActivateSteeringProfileResponse,
  AdjustManualAssistanceData,
  AdjustManualAssistanceError,
  AdjustManualAssistanceResponse,
  CheckLivenessData,
  CheckLivenessResponse,
  CheckReadinessData,
  CheckReadinessError,
  CheckReadinessResponse,
  ConnectSimulationDeviceData,
  ConnectSimulationDeviceError,
  ConnectSimulationDeviceResponse,
  ConnectSimulationHotspotClientData,
  ConnectSimulationHotspotClientError,
  ConnectSimulationHotspotClientResponse,
  CreateButtonProfileData,
  CreateButtonProfileError,
  CreateButtonProfileResponse,
  CreateSteeringProfileData,
  CreateSteeringProfileError,
  CreateSteeringProfileResponse,
  DeleteButtonProfileData,
  DeleteButtonProfileError,
  DeleteButtonProfileResponse,
  DeleteSteeringProfileData,
  DeleteSteeringProfileError,
  DeleteSteeringProfileResponse,
  DisconnectSimulationDeviceData,
  DisconnectSimulationDeviceError,
  DisconnectSimulationDeviceResponse,
  DisconnectSimulationHotspotClientData,
  DisconnectSimulationHotspotClientError,
  DisconnectSimulationHotspotClientResponse,
  FailNextSimulationHotspotOperationData,
  FailNextSimulationHotspotOperationError,
  FailNextSimulationHotspotOperationResponse,
  GetApplicationSettingsData,
  GetApplicationSettingsError,
  GetApplicationSettingsResponse,
  GetButtonProfileData,
  GetButtonProfileError,
  GetButtonProfileResponse,
  GetRuntimeConfigurationData,
  GetRuntimeConfigurationResponse,
  GetSavedButtonProfileData,
  GetSavedButtonProfileError,
  GetSavedButtonProfileResponse,
  GetSavedSteeringProfileData,
  GetSavedSteeringProfileError,
  GetSavedSteeringProfileResponse,
  GetSimulationCoordinatorPanelData,
  GetSimulationCoordinatorPanelResponse,
  GetSteeringProfileData,
  GetSteeringProfileError,
  GetSteeringProfileResponse,
  ListButtonProfilesData,
  ListButtonProfilesError,
  ListButtonProfilesResponse,
  ListSteeringProfilesData,
  ListSteeringProfilesError,
  ListSteeringProfilesResponse,
  PressSimulationCoordinatorPanelButtonData,
  PressSimulationCoordinatorPanelButtonError,
  PressSimulationCoordinatorPanelButtonResponse,
  PreviewSimulationCoordinatorStatusData,
  PreviewSimulationCoordinatorStatusError,
  PreviewSimulationCoordinatorStatusResponse,
  RebootSimulationDeviceData,
  RebootSimulationDeviceError,
  RebootSimulationDeviceResponse,
  ResetSimulationData,
  ResetSimulationError,
  ResetSimulationResponse,
  SetCoolantTemperatureData,
  SetCoolantTemperatureError,
  SetCoolantTemperatureResponse,
  SetEngineRpmData,
  SetEngineRpmError,
  SetEngineRpmResponse,
  SetManualAssistanceLevelData,
  SetManualAssistanceLevelError,
  SetManualAssistanceLevelResponse,
  SetMaximumAssistanceData,
  SetMaximumAssistanceError,
  SetMaximumAssistanceResponse,
  SetOilTemperatureData,
  SetOilTemperatureError,
  SetOilTemperatureResponse,
  SetSimulationDeviceProtocolVersionData,
  SetSimulationDeviceProtocolVersionError,
  SetSimulationDeviceProtocolVersionResponse,
  SetSimulationDeviceStatusCodeData,
  SetSimulationDeviceStatusCodeError,
  SetSimulationDeviceStatusCodeResponse,
  SetSteeringModeData,
  SetSteeringModeError,
  SetSteeringModeResponse,
  SetVehicleSpeedData,
  SetVehicleSpeedError,
  SetVehicleSpeedResponse,
  SetVehicleSweepData,
  SetVehicleSweepError,
  SetVehicleSweepResponse,
  SilenceCoolantTemperatureData,
  SilenceCoolantTemperatureError,
  SilenceCoolantTemperatureResponse,
  SilenceEngineRpmData,
  SilenceEngineRpmError,
  SilenceEngineRpmResponse,
  SilenceOilTemperatureData,
  SilenceOilTemperatureError,
  SilenceOilTemperatureResponse,
  SilenceVehicleSpeedData,
  SilenceVehicleSpeedError,
  SilenceVehicleSpeedResponse,
  TapSimulationButtonData,
  TapSimulationButtonError,
  TapSimulationButtonResponse,
  UpdateApplicationSettingsData,
  UpdateApplicationSettingsError,
  UpdateApplicationSettingsResponse,
  UpdateButtonProfileData,
  UpdateButtonProfileError,
  UpdateButtonProfileResponse,
  UpdateSteeringProfileData,
  UpdateSteeringProfileError,
  UpdateSteeringProfileResponse,
} from "../types.gen"

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const getSavedButtonProfileQueryKey = (
  options?: Options<GetSavedButtonProfileData>
) => createQueryKey("getSavedButtonProfile", options)

/**
 * Get Saved Button Profile
 */
export const getSavedButtonProfileOptions = (
  options?: Options<GetSavedButtonProfileData>
) =>
  queryOptions<
    GetSavedButtonProfileResponse,
    GetSavedButtonProfileError,
    GetSavedButtonProfileResponse,
    ReturnType<typeof getSavedButtonProfileQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) =>
      await getSavedButtonProfile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      }),
    queryKey: getSavedButtonProfileQueryKey(options),
  })

export const listButtonProfilesQueryKey = (
  options?: Options<ListButtonProfilesData>
) => createQueryKey("listButtonProfiles", options)

/**
 * List Button Profiles
 */
export const listButtonProfilesOptions = (
  options?: Options<ListButtonProfilesData>
) =>
  queryOptions<
    ListButtonProfilesResponse,
    ListButtonProfilesError,
    ListButtonProfilesResponse,
    ReturnType<typeof listButtonProfilesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) =>
      await listButtonProfiles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      }),
    queryKey: listButtonProfilesQueryKey(options),
  })

/**
 * Create Button Profile
 */
export const createButtonProfileMutation = (
  options?: Partial<Options<CreateButtonProfileData>>
): UseMutationOptions<
  CreateButtonProfileResponse,
  CreateButtonProfileError,
  Options<CreateButtonProfileData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateButtonProfileResponse,
    CreateButtonProfileError,
    Options<CreateButtonProfileData>
  > = {
    mutationFn: async (fnOptions) =>
      await createButtonProfile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Delete Button Profile
 */
export const deleteButtonProfileMutation = (
  options?: Partial<Options<DeleteButtonProfileData>>
): UseMutationOptions<
  DeleteButtonProfileResponse,
  DeleteButtonProfileError,
  Options<DeleteButtonProfileData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteButtonProfileResponse,
    DeleteButtonProfileError,
    Options<DeleteButtonProfileData>
  > = {
    mutationFn: async (fnOptions) =>
      await deleteButtonProfile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

export const getButtonProfileQueryKey = (
  options: Options<GetButtonProfileData>
) => createQueryKey("getButtonProfile", options)

/**
 * Get Button Profile
 */
export const getButtonProfileOptions = (
  options: Options<GetButtonProfileData>
) =>
  queryOptions<
    GetButtonProfileResponse,
    GetButtonProfileError,
    GetButtonProfileResponse,
    ReturnType<typeof getButtonProfileQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) =>
      await getButtonProfile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      }),
    queryKey: getButtonProfileQueryKey(options),
  })

/**
 * Update Button Profile
 */
export const updateButtonProfileMutation = (
  options?: Partial<Options<UpdateButtonProfileData>>
): UseMutationOptions<
  UpdateButtonProfileResponse,
  UpdateButtonProfileError,
  Options<UpdateButtonProfileData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateButtonProfileResponse,
    UpdateButtonProfileError,
    Options<UpdateButtonProfileData>
  > = {
    mutationFn: async (fnOptions) =>
      await updateButtonProfile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

export const getSimulationCoordinatorPanelQueryKey = (
  options?: Options<GetSimulationCoordinatorPanelData>
) => createQueryKey("getSimulationCoordinatorPanel", options)

/**
 * Get Panel
 */
export const getSimulationCoordinatorPanelOptions = (
  options?: Options<GetSimulationCoordinatorPanelData>
) =>
  queryOptions<
    GetSimulationCoordinatorPanelResponse,
    DefaultError,
    GetSimulationCoordinatorPanelResponse,
    ReturnType<typeof getSimulationCoordinatorPanelQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) =>
      await getSimulationCoordinatorPanel({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      }),
    queryKey: getSimulationCoordinatorPanelQueryKey(options),
  })

/**
 * Press Button
 */
export const pressSimulationCoordinatorPanelButtonMutation = (
  options?: Partial<Options<PressSimulationCoordinatorPanelButtonData>>
): UseMutationOptions<
  PressSimulationCoordinatorPanelButtonResponse,
  PressSimulationCoordinatorPanelButtonError,
  Options<PressSimulationCoordinatorPanelButtonData>
> => {
  const mutationOptions: UseMutationOptions<
    PressSimulationCoordinatorPanelButtonResponse,
    PressSimulationCoordinatorPanelButtonError,
    Options<PressSimulationCoordinatorPanelButtonData>
  > = {
    mutationFn: async (fnOptions) =>
      await pressSimulationCoordinatorPanelButton({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Connect Client
 */
export const connectSimulationHotspotClientMutation = (
  options?: Partial<Options<ConnectSimulationHotspotClientData>>
): UseMutationOptions<
  ConnectSimulationHotspotClientResponse,
  ConnectSimulationHotspotClientError,
  Options<ConnectSimulationHotspotClientData>
> => {
  const mutationOptions: UseMutationOptions<
    ConnectSimulationHotspotClientResponse,
    ConnectSimulationHotspotClientError,
    Options<ConnectSimulationHotspotClientData>
  > = {
    mutationFn: async (fnOptions) =>
      await connectSimulationHotspotClient({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Disconnect Client
 */
export const disconnectSimulationHotspotClientMutation = (
  options?: Partial<Options<DisconnectSimulationHotspotClientData>>
): UseMutationOptions<
  DisconnectSimulationHotspotClientResponse,
  DisconnectSimulationHotspotClientError,
  Options<DisconnectSimulationHotspotClientData>
> => {
  const mutationOptions: UseMutationOptions<
    DisconnectSimulationHotspotClientResponse,
    DisconnectSimulationHotspotClientError,
    Options<DisconnectSimulationHotspotClientData>
  > = {
    mutationFn: async (fnOptions) =>
      await disconnectSimulationHotspotClient({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Preview Coordinator Status
 */
export const previewSimulationCoordinatorStatusMutation = (
  options?: Partial<Options<PreviewSimulationCoordinatorStatusData>>
): UseMutationOptions<
  PreviewSimulationCoordinatorStatusResponse,
  PreviewSimulationCoordinatorStatusError,
  Options<PreviewSimulationCoordinatorStatusData>
> => {
  const mutationOptions: UseMutationOptions<
    PreviewSimulationCoordinatorStatusResponse,
    PreviewSimulationCoordinatorStatusError,
    Options<PreviewSimulationCoordinatorStatusData>
  > = {
    mutationFn: async (fnOptions) =>
      await previewSimulationCoordinatorStatus({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Fail Next Operation
 */
export const failNextSimulationHotspotOperationMutation = (
  options?: Partial<Options<FailNextSimulationHotspotOperationData>>
): UseMutationOptions<
  FailNextSimulationHotspotOperationResponse,
  FailNextSimulationHotspotOperationError,
  Options<FailNextSimulationHotspotOperationData>
> => {
  const mutationOptions: UseMutationOptions<
    FailNextSimulationHotspotOperationResponse,
    FailNextSimulationHotspotOperationError,
    Options<FailNextSimulationHotspotOperationData>
  > = {
    mutationFn: async (fnOptions) =>
      await failNextSimulationHotspotOperation({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Tap Button
 */
export const tapSimulationButtonMutation = (
  options?: Partial<Options<TapSimulationButtonData>>
): UseMutationOptions<
  TapSimulationButtonResponse,
  TapSimulationButtonError,
  Options<TapSimulationButtonData>
> => {
  const mutationOptions: UseMutationOptions<
    TapSimulationButtonResponse,
    TapSimulationButtonError,
    Options<TapSimulationButtonData>
  > = {
    mutationFn: async (fnOptions) =>
      await tapSimulationButton({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Connect Device
 */
export const connectSimulationDeviceMutation = (
  options?: Partial<Options<ConnectSimulationDeviceData>>
): UseMutationOptions<
  ConnectSimulationDeviceResponse,
  ConnectSimulationDeviceError,
  Options<ConnectSimulationDeviceData>
> => {
  const mutationOptions: UseMutationOptions<
    ConnectSimulationDeviceResponse,
    ConnectSimulationDeviceError,
    Options<ConnectSimulationDeviceData>
  > = {
    mutationFn: async (fnOptions) =>
      await connectSimulationDevice({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Disconnect Device
 */
export const disconnectSimulationDeviceMutation = (
  options?: Partial<Options<DisconnectSimulationDeviceData>>
): UseMutationOptions<
  DisconnectSimulationDeviceResponse,
  DisconnectSimulationDeviceError,
  Options<DisconnectSimulationDeviceData>
> => {
  const mutationOptions: UseMutationOptions<
    DisconnectSimulationDeviceResponse,
    DisconnectSimulationDeviceError,
    Options<DisconnectSimulationDeviceData>
  > = {
    mutationFn: async (fnOptions) =>
      await disconnectSimulationDevice({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Set Device Protocol Version
 */
export const setSimulationDeviceProtocolVersionMutation = (
  options?: Partial<Options<SetSimulationDeviceProtocolVersionData>>
): UseMutationOptions<
  SetSimulationDeviceProtocolVersionResponse,
  SetSimulationDeviceProtocolVersionError,
  Options<SetSimulationDeviceProtocolVersionData>
> => {
  const mutationOptions: UseMutationOptions<
    SetSimulationDeviceProtocolVersionResponse,
    SetSimulationDeviceProtocolVersionError,
    Options<SetSimulationDeviceProtocolVersionData>
  > = {
    mutationFn: async (fnOptions) =>
      await setSimulationDeviceProtocolVersion({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Reboot Device
 */
export const rebootSimulationDeviceMutation = (
  options?: Partial<Options<RebootSimulationDeviceData>>
): UseMutationOptions<
  RebootSimulationDeviceResponse,
  RebootSimulationDeviceError,
  Options<RebootSimulationDeviceData>
> => {
  const mutationOptions: UseMutationOptions<
    RebootSimulationDeviceResponse,
    RebootSimulationDeviceError,
    Options<RebootSimulationDeviceData>
  > = {
    mutationFn: async (fnOptions) =>
      await rebootSimulationDevice({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Set Device Status Code
 */
export const setSimulationDeviceStatusCodeMutation = (
  options?: Partial<Options<SetSimulationDeviceStatusCodeData>>
): UseMutationOptions<
  SetSimulationDeviceStatusCodeResponse,
  SetSimulationDeviceStatusCodeError,
  Options<SetSimulationDeviceStatusCodeData>
> => {
  const mutationOptions: UseMutationOptions<
    SetSimulationDeviceStatusCodeResponse,
    SetSimulationDeviceStatusCodeError,
    Options<SetSimulationDeviceStatusCodeData>
  > = {
    mutationFn: async (fnOptions) =>
      await setSimulationDeviceStatusCode({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Reset
 */
export const resetSimulationMutation = (
  options?: Partial<Options<ResetSimulationData>>
): UseMutationOptions<
  ResetSimulationResponse,
  ResetSimulationError,
  Options<ResetSimulationData>
> => {
  const mutationOptions: UseMutationOptions<
    ResetSimulationResponse,
    ResetSimulationError,
    Options<ResetSimulationData>
  > = {
    mutationFn: async (fnOptions) =>
      await resetSimulation({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Set Coolant Temperature
 */
export const setCoolantTemperatureMutation = (
  options?: Partial<Options<SetCoolantTemperatureData>>
): UseMutationOptions<
  SetCoolantTemperatureResponse,
  SetCoolantTemperatureError,
  Options<SetCoolantTemperatureData>
> => {
  const mutationOptions: UseMutationOptions<
    SetCoolantTemperatureResponse,
    SetCoolantTemperatureError,
    Options<SetCoolantTemperatureData>
  > = {
    mutationFn: async (fnOptions) =>
      await setCoolantTemperature({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Silence Coolant Temperature
 */
export const silenceCoolantTemperatureMutation = (
  options?: Partial<Options<SilenceCoolantTemperatureData>>
): UseMutationOptions<
  SilenceCoolantTemperatureResponse,
  SilenceCoolantTemperatureError,
  Options<SilenceCoolantTemperatureData>
> => {
  const mutationOptions: UseMutationOptions<
    SilenceCoolantTemperatureResponse,
    SilenceCoolantTemperatureError,
    Options<SilenceCoolantTemperatureData>
  > = {
    mutationFn: async (fnOptions) =>
      await silenceCoolantTemperature({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Set Oil Temperature
 */
export const setOilTemperatureMutation = (
  options?: Partial<Options<SetOilTemperatureData>>
): UseMutationOptions<
  SetOilTemperatureResponse,
  SetOilTemperatureError,
  Options<SetOilTemperatureData>
> => {
  const mutationOptions: UseMutationOptions<
    SetOilTemperatureResponse,
    SetOilTemperatureError,
    Options<SetOilTemperatureData>
  > = {
    mutationFn: async (fnOptions) =>
      await setOilTemperature({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Silence Oil Temperature
 */
export const silenceOilTemperatureMutation = (
  options?: Partial<Options<SilenceOilTemperatureData>>
): UseMutationOptions<
  SilenceOilTemperatureResponse,
  SilenceOilTemperatureError,
  Options<SilenceOilTemperatureData>
> => {
  const mutationOptions: UseMutationOptions<
    SilenceOilTemperatureResponse,
    SilenceOilTemperatureError,
    Options<SilenceOilTemperatureData>
  > = {
    mutationFn: async (fnOptions) =>
      await silenceOilTemperature({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Set Engine Rpm
 */
export const setEngineRpmMutation = (
  options?: Partial<Options<SetEngineRpmData>>
): UseMutationOptions<
  SetEngineRpmResponse,
  SetEngineRpmError,
  Options<SetEngineRpmData>
> => {
  const mutationOptions: UseMutationOptions<
    SetEngineRpmResponse,
    SetEngineRpmError,
    Options<SetEngineRpmData>
  > = {
    mutationFn: async (fnOptions) =>
      await setEngineRpm({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Silence Engine Rpm
 */
export const silenceEngineRpmMutation = (
  options?: Partial<Options<SilenceEngineRpmData>>
): UseMutationOptions<
  SilenceEngineRpmResponse,
  SilenceEngineRpmError,
  Options<SilenceEngineRpmData>
> => {
  const mutationOptions: UseMutationOptions<
    SilenceEngineRpmResponse,
    SilenceEngineRpmError,
    Options<SilenceEngineRpmData>
  > = {
    mutationFn: async (fnOptions) =>
      await silenceEngineRpm({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Set Vehicle Speed
 */
export const setVehicleSpeedMutation = (
  options?: Partial<Options<SetVehicleSpeedData>>
): UseMutationOptions<
  SetVehicleSpeedResponse,
  SetVehicleSpeedError,
  Options<SetVehicleSpeedData>
> => {
  const mutationOptions: UseMutationOptions<
    SetVehicleSpeedResponse,
    SetVehicleSpeedError,
    Options<SetVehicleSpeedData>
  > = {
    mutationFn: async (fnOptions) =>
      await setVehicleSpeed({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Silence Vehicle Speed
 */
export const silenceVehicleSpeedMutation = (
  options?: Partial<Options<SilenceVehicleSpeedData>>
): UseMutationOptions<
  SilenceVehicleSpeedResponse,
  SilenceVehicleSpeedError,
  Options<SilenceVehicleSpeedData>
> => {
  const mutationOptions: UseMutationOptions<
    SilenceVehicleSpeedResponse,
    SilenceVehicleSpeedError,
    Options<SilenceVehicleSpeedData>
  > = {
    mutationFn: async (fnOptions) =>
      await silenceVehicleSpeed({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Set Vehicle Sweep
 */
export const setVehicleSweepMutation = (
  options?: Partial<Options<SetVehicleSweepData>>
): UseMutationOptions<
  SetVehicleSweepResponse,
  SetVehicleSweepError,
  Options<SetVehicleSweepData>
> => {
  const mutationOptions: UseMutationOptions<
    SetVehicleSweepResponse,
    SetVehicleSweepError,
    Options<SetVehicleSweepData>
  > = {
    mutationFn: async (fnOptions) =>
      await setVehicleSweep({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

export const getRuntimeConfigurationQueryKey = (
  options?: Options<GetRuntimeConfigurationData>
) => createQueryKey("getRuntimeConfiguration", options)

/**
 * Runtime Configuration
 */
export const getRuntimeConfigurationOptions = (
  options?: Options<GetRuntimeConfigurationData>
) =>
  queryOptions<
    GetRuntimeConfigurationResponse,
    DefaultError,
    GetRuntimeConfigurationResponse,
    ReturnType<typeof getRuntimeConfigurationQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) =>
      await getRuntimeConfiguration({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      }),
    queryKey: getRuntimeConfigurationQueryKey(options),
  })

export const getApplicationSettingsQueryKey = (
  options?: Options<GetApplicationSettingsData>
) => createQueryKey("getApplicationSettings", options)

/**
 * Get Application Settings
 */
export const getApplicationSettingsOptions = (
  options?: Options<GetApplicationSettingsData>
) =>
  queryOptions<
    GetApplicationSettingsResponse,
    GetApplicationSettingsError,
    GetApplicationSettingsResponse,
    ReturnType<typeof getApplicationSettingsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) =>
      await getApplicationSettings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      }),
    queryKey: getApplicationSettingsQueryKey(options),
  })

/**
 * Update Application Settings
 */
export const updateApplicationSettingsMutation = (
  options?: Partial<Options<UpdateApplicationSettingsData>>
): UseMutationOptions<
  UpdateApplicationSettingsResponse,
  UpdateApplicationSettingsError,
  Options<UpdateApplicationSettingsData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateApplicationSettingsResponse,
    UpdateApplicationSettingsError,
    Options<UpdateApplicationSettingsData>
  > = {
    mutationFn: async (fnOptions) =>
      await updateApplicationSettings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Activate Steering Profile
 */
export const activateSteeringProfileMutation = (
  options?: Partial<Options<ActivateSteeringProfileData>>
): UseMutationOptions<
  ActivateSteeringProfileResponse,
  ActivateSteeringProfileError,
  Options<ActivateSteeringProfileData>
> => {
  const mutationOptions: UseMutationOptions<
    ActivateSteeringProfileResponse,
    ActivateSteeringProfileError,
    Options<ActivateSteeringProfileData>
  > = {
    mutationFn: async (fnOptions) =>
      await activateSteeringProfile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Activate Steering Curve
 */
export const activateSteeringCurveMutation = (
  options?: Partial<Options<ActivateSteeringCurveData>>
): UseMutationOptions<
  ActivateSteeringCurveResponse,
  ActivateSteeringCurveError,
  Options<ActivateSteeringCurveData>
> => {
  const mutationOptions: UseMutationOptions<
    ActivateSteeringCurveResponse,
    ActivateSteeringCurveError,
    Options<ActivateSteeringCurveData>
  > = {
    mutationFn: async (fnOptions) =>
      await activateSteeringCurve({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Adjust Manual Assistance
 */
export const adjustManualAssistanceMutation = (
  options?: Partial<Options<AdjustManualAssistanceData>>
): UseMutationOptions<
  AdjustManualAssistanceResponse,
  AdjustManualAssistanceError,
  Options<AdjustManualAssistanceData>
> => {
  const mutationOptions: UseMutationOptions<
    AdjustManualAssistanceResponse,
    AdjustManualAssistanceError,
    Options<AdjustManualAssistanceData>
  > = {
    mutationFn: async (fnOptions) =>
      await adjustManualAssistance({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Set Manual Assistance Level
 */
export const setManualAssistanceLevelMutation = (
  options?: Partial<Options<SetManualAssistanceLevelData>>
): UseMutationOptions<
  SetManualAssistanceLevelResponse,
  SetManualAssistanceLevelError,
  Options<SetManualAssistanceLevelData>
> => {
  const mutationOptions: UseMutationOptions<
    SetManualAssistanceLevelResponse,
    SetManualAssistanceLevelError,
    Options<SetManualAssistanceLevelData>
  > = {
    mutationFn: async (fnOptions) =>
      await setManualAssistanceLevel({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Set Maximum Assistance
 */
export const setMaximumAssistanceMutation = (
  options?: Partial<Options<SetMaximumAssistanceData>>
): UseMutationOptions<
  SetMaximumAssistanceResponse,
  SetMaximumAssistanceError,
  Options<SetMaximumAssistanceData>
> => {
  const mutationOptions: UseMutationOptions<
    SetMaximumAssistanceResponse,
    SetMaximumAssistanceError,
    Options<SetMaximumAssistanceData>
  > = {
    mutationFn: async (fnOptions) =>
      await setMaximumAssistance({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Set Steering Mode
 */
export const setSteeringModeMutation = (
  options?: Partial<Options<SetSteeringModeData>>
): UseMutationOptions<
  SetSteeringModeResponse,
  SetSteeringModeError,
  Options<SetSteeringModeData>
> => {
  const mutationOptions: UseMutationOptions<
    SetSteeringModeResponse,
    SetSteeringModeError,
    Options<SetSteeringModeData>
  > = {
    mutationFn: async (fnOptions) =>
      await setSteeringMode({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

export const getSavedSteeringProfileQueryKey = (
  options?: Options<GetSavedSteeringProfileData>
) => createQueryKey("getSavedSteeringProfile", options)

/**
 * Get Saved Steering Profile
 */
export const getSavedSteeringProfileOptions = (
  options?: Options<GetSavedSteeringProfileData>
) =>
  queryOptions<
    GetSavedSteeringProfileResponse,
    GetSavedSteeringProfileError,
    GetSavedSteeringProfileResponse,
    ReturnType<typeof getSavedSteeringProfileQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) =>
      await getSavedSteeringProfile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      }),
    queryKey: getSavedSteeringProfileQueryKey(options),
  })

export const listSteeringProfilesQueryKey = (
  options?: Options<ListSteeringProfilesData>
) => createQueryKey("listSteeringProfiles", options)

/**
 * List Steering Profiles
 */
export const listSteeringProfilesOptions = (
  options?: Options<ListSteeringProfilesData>
) =>
  queryOptions<
    ListSteeringProfilesResponse,
    ListSteeringProfilesError,
    ListSteeringProfilesResponse,
    ReturnType<typeof listSteeringProfilesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) =>
      await listSteeringProfiles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      }),
    queryKey: listSteeringProfilesQueryKey(options),
  })

/**
 * Create Steering Profile
 */
export const createSteeringProfileMutation = (
  options?: Partial<Options<CreateSteeringProfileData>>
): UseMutationOptions<
  CreateSteeringProfileResponse,
  CreateSteeringProfileError,
  Options<CreateSteeringProfileData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateSteeringProfileResponse,
    CreateSteeringProfileError,
    Options<CreateSteeringProfileData>
  > = {
    mutationFn: async (fnOptions) =>
      await createSteeringProfile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

/**
 * Delete Steering Profile
 */
export const deleteSteeringProfileMutation = (
  options?: Partial<Options<DeleteSteeringProfileData>>
): UseMutationOptions<
  DeleteSteeringProfileResponse,
  DeleteSteeringProfileError,
  Options<DeleteSteeringProfileData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteSteeringProfileResponse,
    DeleteSteeringProfileError,
    Options<DeleteSteeringProfileData>
  > = {
    mutationFn: async (fnOptions) =>
      await deleteSteeringProfile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

export const getSteeringProfileQueryKey = (
  options: Options<GetSteeringProfileData>
) => createQueryKey("getSteeringProfile", options)

/**
 * Get Steering Profile
 */
export const getSteeringProfileOptions = (
  options: Options<GetSteeringProfileData>
) =>
  queryOptions<
    GetSteeringProfileResponse,
    GetSteeringProfileError,
    GetSteeringProfileResponse,
    ReturnType<typeof getSteeringProfileQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) =>
      await getSteeringProfile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      }),
    queryKey: getSteeringProfileQueryKey(options),
  })

/**
 * Update Steering Profile
 */
export const updateSteeringProfileMutation = (
  options?: Partial<Options<UpdateSteeringProfileData>>
): UseMutationOptions<
  UpdateSteeringProfileResponse,
  UpdateSteeringProfileError,
  Options<UpdateSteeringProfileData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateSteeringProfileResponse,
    UpdateSteeringProfileError,
    Options<UpdateSteeringProfileData>
  > = {
    mutationFn: async (fnOptions) =>
      await updateSteeringProfile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      }),
  }
  return mutationOptions
}

export const checkLivenessQueryKey = (options?: Options<CheckLivenessData>) =>
  createQueryKey("checkLiveness", options)

/**
 * Live
 */
export const checkLivenessOptions = (options?: Options<CheckLivenessData>) =>
  queryOptions<
    CheckLivenessResponse,
    DefaultError,
    CheckLivenessResponse,
    ReturnType<typeof checkLivenessQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) =>
      await checkLiveness({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      }),
    queryKey: checkLivenessQueryKey(options),
  })

export const checkReadinessQueryKey = (options?: Options<CheckReadinessData>) =>
  createQueryKey("checkReadiness", options)

/**
 * Ready
 */
export const checkReadinessOptions = (options?: Options<CheckReadinessData>) =>
  queryOptions<
    CheckReadinessResponse,
    CheckReadinessError,
    CheckReadinessResponse,
    ReturnType<typeof checkReadinessQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) =>
      await checkReadiness({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      }),
    queryKey: checkReadinessQueryKey(options),
  })
