/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevRouteRouteImport } from './routes/dev/route'
import { Route as CarRouteRouteImport } from './routes/car/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as CarIndexRouteImport } from './routes/car/index'
import { Route as CarSteeringIndexRouteImport } from './routes/car/steering/index'
import { Route as CarSettingsIndexRouteImport } from './routes/car/settings/index'
import { Route as CarDriveIndexRouteImport } from './routes/car/drive/index'

const DevRouteRoute = DevRouteRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const CarRouteRoute = CarRouteRouteImport.update({
  id: '/car',
  path: '/car',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRouteRoute,
} as any)
const CarIndexRoute = CarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarRouteRoute,
} as any)
const CarSteeringIndexRoute = CarSteeringIndexRouteImport.update({
  id: '/steering/',
  path: '/steering/',
  getParentRoute: () => CarRouteRoute,
} as any)
const CarSettingsIndexRoute = CarSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => CarRouteRoute,
} as any)
const CarDriveIndexRoute = CarDriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => CarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/car': typeof CarRouteRouteWithChildren
  '/dev': typeof DevRouteRouteWithChildren
  '/car/': typeof CarIndexRoute
  '/dev/': typeof DevIndexRoute
  '/car/drive/': typeof CarDriveIndexRoute
  '/car/settings/': typeof CarSettingsIndexRoute
  '/car/steering/': typeof CarSteeringIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/car': typeof CarIndexRoute
  '/dev': typeof DevIndexRoute
  '/car/drive': typeof CarDriveIndexRoute
  '/car/settings': typeof CarSettingsIndexRoute
  '/car/steering': typeof CarSteeringIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/car': typeof CarRouteRouteWithChildren
  '/dev': typeof DevRouteRouteWithChildren
  '/car/': typeof CarIndexRoute
  '/dev/': typeof DevIndexRoute
  '/car/drive/': typeof CarDriveIndexRoute
  '/car/settings/': typeof CarSettingsIndexRoute
  '/car/steering/': typeof CarSteeringIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/car'
    | '/dev'
    | '/car/'
    | '/dev/'
    | '/car/drive/'
    | '/car/settings/'
    | '/car/steering/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/car' | '/dev' | '/car/drive' | '/car/settings' | '/car/steering'
  id:
    | '__root__'
    | '/'
    | '/car'
    | '/dev'
    | '/car/'
    | '/dev/'
    | '/car/drive/'
    | '/car/settings/'
    | '/car/steering/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarRouteRoute: typeof CarRouteRouteWithChildren
  DevRouteRoute: typeof DevRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car': {
      id: '/car'
      path: '/car'
      fullPath: '/car'
      preLoaderRoute: typeof CarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/car/': {
      id: '/car/'
      path: '/'
      fullPath: '/car/'
      preLoaderRoute: typeof CarIndexRouteImport
      parentRoute: typeof CarRouteRoute
    }
    '/car/steering/': {
      id: '/car/steering/'
      path: '/steering'
      fullPath: '/car/steering/'
      preLoaderRoute: typeof CarSteeringIndexRouteImport
      parentRoute: typeof CarRouteRoute
    }
    '/car/settings/': {
      id: '/car/settings/'
      path: '/settings'
      fullPath: '/car/settings/'
      preLoaderRoute: typeof CarSettingsIndexRouteImport
      parentRoute: typeof CarRouteRoute
    }
    '/car/drive/': {
      id: '/car/drive/'
      path: '/drive'
      fullPath: '/car/drive/'
      preLoaderRoute: typeof CarDriveIndexRouteImport
      parentRoute: typeof CarRouteRoute
    }
  }
}

interface CarRouteRouteChildren {
  CarIndexRoute: typeof CarIndexRoute
  CarDriveIndexRoute: typeof CarDriveIndexRoute
  CarSettingsIndexRoute: typeof CarSettingsIndexRoute
  CarSteeringIndexRoute: typeof CarSteeringIndexRoute
}

const CarRouteRouteChildren: CarRouteRouteChildren = {
  CarIndexRoute: CarIndexRoute,
  CarDriveIndexRoute: CarDriveIndexRoute,
  CarSettingsIndexRoute: CarSettingsIndexRoute,
  CarSteeringIndexRoute: CarSteeringIndexRoute,
}

const CarRouteRouteWithChildren = CarRouteRoute._addFileChildren(
  CarRouteRouteChildren,
)

interface DevRouteRouteChildren {
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteRouteChildren: DevRouteRouteChildren = {
  DevIndexRoute: DevIndexRoute,
}

const DevRouteRouteWithChildren = DevRouteRoute._addFileChildren(
  DevRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarRouteRoute: CarRouteRouteWithChildren,
  DevRouteRoute: DevRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
