"""Generate the provisional project protocol artifacts from protocol/custom.toml."""

from __future__ import annotations

import argparse
import tomllib
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

GENERATED_NOTICE = "Generated by scripts/generate_custom_protocol.py; do not edit."
MARKDOWN_START = "<!-- BEGIN GENERATED CUSTOM PROTOCOL -->"
MARKDOWN_END = "<!-- END GENERATED CUSTOM PROTOCOL -->"


@dataclass(frozen=True)
class MessageDefinition:
    can_id: int
    length: int
    direction: str
    purpose: str
    byte_positions: tuple[tuple[str, int], ...]
    values: tuple[tuple[str, int], ...]
    led_count: int | None = None
    even_index_shift: int | None = None
    odd_index_shift: int | None = None
    nibble_mask: int | None = None


@dataclass(frozen=True)
class ProtocolDefinition:
    button_event: MessageDefinition
    led_snapshot: MessageDefinition


def load_definition(path: Path) -> ProtocolDefinition:
    with path.open("rb") as source:
        raw = tomllib.load(source)
    return ProtocolDefinition(
        button_event=_parse_message(raw, "button_event"),
        led_snapshot=_parse_led_snapshot(raw),
    )


def _parse_message(raw: Mapping[str, Any], name: str) -> MessageDefinition:
    table = raw.get(name)
    if not isinstance(table, dict):
        raise ValueError(f"missing [{name}] table")
    byte_positions = _integer_items(table, "bytes", name)
    values = _integer_items(table, "values", name)
    can_id = table.get("can_id")
    length = table.get("length")
    direction = table.get("direction")
    purpose = table.get("purpose")
    if not isinstance(can_id, int) or not 0 <= can_id <= 0x7FF:
        raise ValueError(f"{name}.can_id must be a standard CAN ID")
    if not isinstance(length, int) or not 1 <= length <= 8:
        raise ValueError(f"{name}.length must be between 1 and 8")
    if not isinstance(direction, str) or not isinstance(purpose, str):
        raise ValueError(f"{name} direction and purpose must be strings")
    if len({position for _, position in byte_positions}) != len(byte_positions):
        raise ValueError(f"{name} byte positions must be unique")
    if any(not 0 <= position < length for _, position in byte_positions):
        raise ValueError(f"{name} byte position exceeds payload length")
    if any(not 0 <= value <= 0xFF for _, value in values):
        raise ValueError(f"{name} values must fit in one byte")
    return MessageDefinition(can_id, length, direction, purpose, byte_positions, values)


def _parse_led_snapshot(raw: Mapping[str, Any]) -> MessageDefinition:
    name = "led_snapshot"
    table = raw.get(name)
    if not isinstance(table, dict):
        raise ValueError(f"missing [{name}] table")
    values = _integer_items(table, "values", name)
    can_id = table.get("can_id")
    length = table.get("length")
    direction = table.get("direction")
    purpose = table.get("purpose")
    led_count = table.get("led_count")
    even_index_shift = table.get("even_index_shift")
    odd_index_shift = table.get("odd_index_shift")
    nibble_mask = table.get("nibble_mask")
    if not isinstance(can_id, int) or not 0 <= can_id <= 0x7FF:
        raise ValueError(f"{name}.can_id must be a standard CAN ID")
    if length != 8 or led_count != 16:
        raise ValueError("led_snapshot must contain 16 LEDs in 8 bytes")
    if (even_index_shift, odd_index_shift, nibble_mask) != (0, 4, 0x0F):
        raise ValueError("led_snapshot must use even/low and odd/high nibble ordering")
    if not isinstance(direction, str) or not isinstance(purpose, str):
        raise ValueError(f"{name} direction and purpose must be strings")
    if tuple(value for _, value in values) != tuple(range(len(values))):
        raise ValueError("led_snapshot colour codes must be contiguous from zero")
    if max(value for _, value in values) > nibble_mask:
        raise ValueError("led_snapshot colour codes must fit in one nibble")
    return MessageDefinition(
        can_id,
        length,
        direction,
        purpose,
        (),
        values,
        led_count,
        even_index_shift,
        odd_index_shift,
        nibble_mask,
    )


def _integer_items(
    table: Mapping[str, Any], section: str, message_name: str
) -> tuple[tuple[str, int], ...]:
    values = table.get(section)
    if not isinstance(values, dict) or not values:
        raise ValueError(f"missing [{message_name}.{section}] table")
    if not all(isinstance(name, str) and isinstance(value, int) for name, value in values.items()):
        raise ValueError(f"{message_name}.{section} values must be integers")
    return tuple(values.items())


def render_python(definition: ProtocolDefinition) -> str:
    lines = [
        f'"""{GENERATED_NOTICE}"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    for name, value in _constants(definition):
        if name == "CAN_ID_LED_SNAPSHOT":
            lines.append("")
        lines.append(f"{name} = {_render_value(name, value)}")
    return "\n".join(lines) + "\n"


def _constants(definition: ProtocolDefinition) -> tuple[tuple[str, int], ...]:
    return (
        *_message_constants("BUTTON_EVENT", definition.button_event, "BUTTON"),
        ("CAN_ID_LED_SNAPSHOT", definition.led_snapshot.can_id),
        ("LED_SNAPSHOT_LENGTH", definition.led_snapshot.length),
        ("LED_COUNT", _required(definition.led_snapshot.led_count)),
        ("LED_EVEN_INDEX_SHIFT", _required(definition.led_snapshot.even_index_shift)),
        ("LED_ODD_INDEX_SHIFT", _required(definition.led_snapshot.odd_index_shift)),
        ("LED_NIBBLE_MASK", _required(definition.led_snapshot.nibble_mask)),
        *((f"LED_COLOUR_{name.upper()}", value) for name, value in definition.led_snapshot.values),
        ("LED_COLOUR_MAX", max(value for _, value in definition.led_snapshot.values)),
    )


def _required(value: int | None) -> int:
    if value is None:
        raise ValueError("missing LED snapshot metadata")
    return value


def _message_constants(
    prefix: str, message: MessageDefinition, value_prefix: str
) -> tuple[tuple[str, int], ...]:
    return (
        (f"CAN_ID_{prefix}", message.can_id),
        *((f"{prefix}_{name.upper()}_BYTE", position) for name, position in message.byte_positions),
        (f"{prefix}_LENGTH", message.length),
        *((f"{value_prefix}_{name.upper()}", value) for name, value in message.values),
    )


def _render_value(name: str, value: int) -> str:
    if name.endswith(("_BYTE", "_LENGTH", "_COUNT", "_SHIFT")):
        return str(value)
    width = 3 if name.startswith("CAN_ID_") else 2
    return f"0x{value:0{width}X}"


def render_header(definition: ProtocolDefinition) -> str:
    declarations: list[str] = []
    for name, value in _constants(definition):
        if name == "CAN_ID_LED_SNAPSHOT":
            declarations.append("")
        value_type = "unsigned long" if name.startswith("CAN_ID_") else "uint8_t"
        declarations.append(
            f"static const {value_type} {name} = {_render_value(name, value)};"
        )
    return "\n".join(
        [
            "#ifndef E87CANBUS_CAN_IDS_H",
            "#define E87CANBUS_CAN_IDS_H",
            "",
            f"// {GENERATED_NOTICE}",
            "#include <Arduino.h>",
            "",
            *declarations,
            "",
            "#endif",
            "",
        ]
    )


def render_markdown_section(definition: ProtocolDefinition) -> str:
    messages = (definition.button_event, definition.led_snapshot)
    lines = [
        MARKDOWN_START,
        f"<!-- {GENERATED_NOTICE} -->",
        "| ID | Direction | Purpose | Length | Payload |",
        "|---|---|---|---:|---|",
    ]
    for message in messages:
        payload = (
            ", ".join(
                f"byte {position} = {name.replace('_', ' ')}"
                for name, position in message.byte_positions
            )
            if message.byte_positions
            else "two LED colour nibbles per byte, even index low"
        )
        lines.append(
            f"| `0x{message.can_id:03X}` | {message.direction} | {message.purpose} "
            f"| {message.length} | {payload} |"
        )
    lines.extend(_markdown_values("Button State Constants", definition.button_event.values))
    lines.extend(_markdown_values("LED Colour Codes", definition.led_snapshot.values))
    lines.append(MARKDOWN_END)
    return "\n".join(lines)


def _markdown_values(title: str, values: tuple[tuple[str, int], ...]) -> list[str]:
    lines = ["", f"## {title}", "", "| Value | Meaning |", "|---|---|"]
    lines.extend(f"| `0x{value:02X}` | {name} |" for name, value in values)
    return lines


def replace_markdown_section(document: str, generated: str) -> str:
    start = document.find(MARKDOWN_START)
    end = document.find(MARKDOWN_END)
    if start < 0 or end < start:
        raise ValueError("custom_ids.md is missing generated section markers")
    end += len(MARKDOWN_END)
    return f"{document[:start]}{generated}{document[end:]}"


def expected_artifacts(root: Path, definition: ProtocolDefinition) -> dict[Path, str]:
    markdown_path = root / "protocol" / "custom_ids.md"
    markdown = replace_markdown_section(
        markdown_path.read_text(), render_markdown_section(definition)
    )
    return {
        root / "coordinator" / "src" / "e87canbus" / "protocol" / "generated.py": render_python(
            definition
        ),
        root / "devices" / "button-pad" / "include" / "can_ids.h": render_header(definition),
        markdown_path: markdown,
    }


def stale_artifacts(root: Path) -> tuple[Path, ...]:
    definition = load_definition(root / "protocol" / "custom.toml")
    return tuple(
        path for path, expected in expected_artifacts(root, definition).items()
        if not path.exists() or path.read_text() != expected
    )


def generate(root: Path) -> None:
    definition = load_definition(root / "protocol" / "custom.toml")
    for path, content in expected_artifacts(root, definition).items():
        path.write_text(content)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated artifacts differ.")
    args = parser.parse_args(argv)
    root = Path(__file__).resolve().parents[1]
    if not args.check:
        generate(root)
        return 0
    stale = stale_artifacts(root)
    for path in stale:
        print(f"out of date: {path.relative_to(root)}")
    return int(bool(stale))


if __name__ == "__main__":
    raise SystemExit(main())
