"""Generate repository-owned project protocol artifacts from custom.toml."""

from __future__ import annotations

import argparse
import tomllib
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

GENERATED_NOTICE = "Generated by scripts/generate_custom_protocol.py; do not edit."
MARKDOWN_START = "<!-- BEGIN GENERATED CUSTOM PROTOCOL -->"
MARKDOWN_END = "<!-- END GENERATED CUSTOM PROTOCOL -->"


@dataclass(frozen=True)
class MessageDefinition:
    name: str
    can_id: int
    length: int
    direction: str
    purpose: str
    payload: str
    byte_positions: tuple[tuple[str, int], ...]
    values: tuple[tuple[str, int], ...]
    values_title: str | None = None
    led_count: int | None = None
    even_index_shift: int | None = None
    odd_index_shift: int | None = None
    nibble_mask: int | None = None


@dataclass(frozen=True)
class TransportLinkDefinition:
    name: str
    coordinator_to_device_id: int
    device_to_coordinator_id: int
    maximum_payload_length: int
    purpose: str


@dataclass(frozen=True)
class ProtocolDefinition:
    protocol_version: int
    messages: tuple[MessageDefinition, ...]
    transport_links: tuple[TransportLinkDefinition, ...]

    def message(self, name: str) -> MessageDefinition:
        for message in self.messages:
            if message.name == name:
                return message
        raise KeyError(name)


def load_definition(path: Path) -> ProtocolDefinition:
    with path.open("rb") as source:
        raw = tomllib.load(source)

    protocol_version = raw.get("protocol_version")
    if not isinstance(protocol_version, int) or not 0 <= protocol_version <= 0x0F:
        raise ValueError("protocol_version must fit in the WELCOME_ACK version nibble")

    messages = tuple(
        _parse_message(name, table)
        for name, table in raw.items()
        if isinstance(table, dict) and "can_id" in table
    )
    if not messages:
        raise ValueError("custom protocol must define at least one message")
    can_ids = [message.can_id for message in messages]
    if len(set(can_ids)) != len(can_ids):
        raise ValueError("custom protocol arbitration IDs must be unique")
    transport_links = tuple(
        _parse_transport_link(name, table)
        for name, table in raw.items()
        if isinstance(table, dict) and "coordinator_to_device_id" in table
    )
    link_ids = [
        can_id
        for link in transport_links
        for can_id in (link.coordinator_to_device_id, link.device_to_coordinator_id)
    ]
    if set(can_ids).intersection(link_ids) or len(set(link_ids)) != len(link_ids):
        raise ValueError("custom protocol arbitration IDs must be unique")
    definition = ProtocolDefinition(protocol_version, messages, transport_links)
    _validate_shared_registry_layouts(definition)
    return definition


def _parse_transport_link(name: str, table: Mapping[str, Any]) -> TransportLinkDefinition:
    coordinator_to_device_id = table.get("coordinator_to_device_id")
    device_to_coordinator_id = table.get("device_to_coordinator_id")
    maximum_payload_length = table.get("maximum_payload_length")
    purpose = table.get("purpose")
    if not all(isinstance(value, int) and 0 <= value <= 0x7FF for value in (
        coordinator_to_device_id, device_to_coordinator_id
    )):
        raise ValueError(f"{name} transport IDs must be standard CAN IDs")
    if coordinator_to_device_id == device_to_coordinator_id:
        raise ValueError(f"{name} transport IDs must differ")
    if not isinstance(maximum_payload_length, int) or not 1 <= maximum_payload_length <= 256:
        raise ValueError(f"{name} maximum payload length must be between 1 and 256")
    if not isinstance(purpose, str):
        raise ValueError(f"{name}.purpose must be a string")
    return TransportLinkDefinition(
        name, coordinator_to_device_id, device_to_coordinator_id, maximum_payload_length, purpose
    )


def _validate_shared_registry_layouts(definition: ProtocolDefinition) -> None:
    """Keep the role-generic Python codecs safe when generated layouts evolve."""

    for suffix in ("hello", "welcome_ack", "heartbeat"):
        button_pad = definition.message(f"button_pad_{suffix}")
        servotronic = definition.message(f"servotronic_controller_{suffix}")
        if (
            button_pad.length != servotronic.length
            or button_pad.byte_positions != servotronic.byte_positions
        ):
            raise ValueError(f"button-pad and Servotronic {suffix} layouts must remain identical")


def _parse_message(name: str, table: Mapping[str, Any]) -> MessageDefinition:
    can_id = table.get("can_id")
    length = table.get("length")
    direction = table.get("direction")
    purpose = table.get("purpose")
    payload = table.get("payload")
    if not isinstance(can_id, int) or not 0 <= can_id <= 0x7FF:
        raise ValueError(f"{name}.can_id must be a standard CAN ID")
    if not isinstance(length, int) or not 1 <= length <= 8:
        raise ValueError(f"{name}.length must be between 1 and 8")
    if not all(isinstance(value, str) for value in (direction, purpose, payload)):
        raise ValueError(f"{name} direction, purpose, and payload must be strings")

    byte_positions = _integer_items(
        table,
        "bytes",
        name,
        required="led_count" not in table,
    )
    values = _integer_items(table, "values", name, required=False)
    if len({position for _, position in byte_positions}) != len(byte_positions):
        raise ValueError(f"{name} byte positions must be unique")
    if any(not 0 <= position < length for _, position in byte_positions):
        raise ValueError(f"{name} byte position exceeds payload length")
    if any(not 0 <= value <= 0xFF for _, value in values):
        raise ValueError(f"{name} values must fit in one byte")

    led_metadata = _parse_led_metadata(name, table, values)
    values_title = table.get("values_title")
    if values_title is not None and not isinstance(values_title, str):
        raise ValueError(f"{name}.values_title must be a string")
    return MessageDefinition(
        name=name,
        can_id=can_id,
        length=length,
        direction=direction,
        purpose=purpose,
        payload=payload,
        byte_positions=byte_positions,
        values=values,
        values_title=values_title,
        **led_metadata,
    )


def _parse_led_metadata(
    name: str,
    table: Mapping[str, Any],
    values: tuple[tuple[str, int], ...],
) -> dict[str, int | None]:
    metadata = tuple(
        table.get(key)
        for key in ("led_count", "even_index_shift", "odd_index_shift", "nibble_mask")
    )
    if all(value is None for value in metadata):
        return {
            "led_count": None,
            "even_index_shift": None,
            "odd_index_shift": None,
            "nibble_mask": None,
        }
    led_count, even_index_shift, odd_index_shift, nibble_mask = metadata
    if not all(isinstance(value, int) for value in metadata):
        raise ValueError(f"{name} LED packing metadata must be integers")
    if (table.get("length"), led_count, even_index_shift, odd_index_shift) != (8, 16, 0, 4):
        raise ValueError("LED snapshot must contain 16 LEDs in 8 bytes with low/high nibbles")
    if nibble_mask != 0x0F:
        raise ValueError("LED snapshot must use a 0x0F nibble mask")
    if not values or tuple(value for _, value in values) != tuple(range(len(values))):
        raise ValueError("LED snapshot colour codes must be contiguous from zero")
    if max(value for _, value in values) > nibble_mask:
        raise ValueError("LED snapshot colour codes must fit in one nibble")
    if table.get("bytes"):
        raise ValueError("LED snapshot packing owns its byte layout")
    return {
        "led_count": led_count,
        "even_index_shift": even_index_shift,
        "odd_index_shift": odd_index_shift,
        "nibble_mask": nibble_mask,
    }


def _integer_items(
    table: Mapping[str, Any],
    section: str,
    message_name: str,
    *,
    required: bool,
) -> tuple[tuple[str, int], ...]:
    values = table.get(section)
    if values is None and not required:
        return ()
    if not isinstance(values, dict) or (required and not values):
        raise ValueError(f"missing [{message_name}.{section}] table")
    if not all(isinstance(name, str) and isinstance(value, int) for name, value in values.items()):
        raise ValueError(f"{message_name}.{section} values must be integers")
    return tuple(values.items())


def render_python(definition: ProtocolDefinition) -> str:
    lines = [
        f'"""{GENERATED_NOTICE}"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    for name, value in _constants(definition):
        lines.append(f"{name} = {_render_value(name, value)}")
    return "\n".join(lines) + "\n"


def _constants(definition: ProtocolDefinition) -> tuple[tuple[str, int], ...]:
    constants: list[tuple[str, int]] = [
        ("CUSTOM_DEVICE_PROTOCOL_VERSION", definition.protocol_version)
    ]
    for message in definition.messages:
        prefix = _constant_prefix(message.name)
        constants.append((f"CAN_ID_{prefix}", message.can_id))
        constants.extend(
            (f"{prefix}_{_constant_fragment(name)}_BYTE", position)
            for name, position in message.byte_positions
        )
        constants.append((f"{prefix}_LENGTH", message.length))
        if message.name == "button_event":
            constants.extend((f"BUTTON_{name.upper()}", value) for name, value in message.values)
        elif message.values and message.name != "led_snapshot":
            constants.extend(
                (f"{prefix}_{name.upper()}", value) for name, value in message.values
            )
        elif message.name == "led_snapshot":
            constants.extend(
                [
                    ("LED_COUNT", _required(message.led_count)),
                    ("LED_EVEN_INDEX_SHIFT", _required(message.even_index_shift)),
                    ("LED_ODD_INDEX_SHIFT", _required(message.odd_index_shift)),
                    ("LED_NIBBLE_MASK", _required(message.nibble_mask)),
                ]
            )
            constants.extend(
                (f"LED_COLOUR_{name.upper()}", value) for name, value in message.values
            )
            constants.append(("LED_COLOUR_MAX", max(value for _, value in message.values)))
    for link in definition.transport_links:
        prefix = _constant_prefix(link.name)
        constants.extend(
            (
                (f"CAN_ID_{prefix}_COORDINATOR_TO_DEVICE", link.coordinator_to_device_id),
                (f"CAN_ID_{prefix}_DEVICE_TO_COORDINATOR", link.device_to_coordinator_id),
                (f"{prefix}_MAXIMUM_PAYLOAD_LENGTH", link.maximum_payload_length),
            )
        )
    return tuple(constants)


def _required(value: int | None) -> int:
    if value is None:
        raise ValueError("missing LED snapshot metadata")
    return value


def _constant_prefix(name: str) -> str:
    return name.upper()


def _constant_fragment(name: str) -> str:
    return name.upper()


def _render_value(name: str, value: int) -> str:
    if name == "CUSTOM_DEVICE_PROTOCOL_VERSION" or name.endswith(
        ("_BYTE", "_LENGTH", "_COUNT", "_SHIFT")
    ):
        return str(value)
    width = 3 if name.startswith("CAN_ID_") else 2
    return f"0x{value:0{width}X}"


def render_header(definition: ProtocolDefinition) -> str:
    declarations: list[str] = []
    for name, value in _constants(definition):
        value_type = (
            "unsigned long"
            if name.startswith("CAN_ID_")
            else "uint16_t"
            if name.endswith("MAXIMUM_PAYLOAD_LENGTH")
            else "uint8_t"
        )
        declarations.append(f"static const {value_type} {name} = {_render_value(name, value)};")
    return "\n".join(
        [
            "#ifndef E87CANBUS_CAN_IDS_H",
            "#define E87CANBUS_CAN_IDS_H",
            "",
            f"// {GENERATED_NOTICE}",
            "#include <Arduino.h>",
            "",
            *declarations,
            "",
            "#endif",
            "",
        ]
    )


def render_markdown_section(definition: ProtocolDefinition) -> str:
    lines = [
        MARKDOWN_START,
        f"<!-- {GENERATED_NOTICE} -->",
        "| ID | Direction | Purpose | Length | Payload |",
        "|---|---|---|---:|---|",
    ]
    for message in definition.messages:
        lines.append(
            f"| `0x{message.can_id:03X}` | {message.direction} | {message.purpose} "
            f"| {message.length} | {message.payload} |"
        )
    for link in definition.transport_links:
        lines.append(
            f"| `0x{link.coordinator_to_device_id:03X}` / "
            f"`0x{link.device_to_coordinator_id:03X}` | "
            f"Coordinator ↔ device | {link.purpose} | variable | ISO-TP; maximum "
            f"{link.maximum_payload_length} reassembled bytes |"
        )
    for message in definition.messages:
        if message.values:
            title = message.values_title or f"{message.name.replace('_', ' ').title()} Values"
            lines.extend(_markdown_values(title, message.values))
    lines.append(MARKDOWN_END)
    return "\n".join(lines)


def _markdown_values(title: str, values: tuple[tuple[str, int], ...]) -> list[str]:
    lines = ["", f"## {title}", "", "| Value | Meaning |", "|---|---|"]
    lines.extend(f"| `0x{value:02X}` | {name} |" for name, value in values)
    return lines


def replace_markdown_section(document: str, generated: str) -> str:
    start = document.find(MARKDOWN_START)
    end = document.find(MARKDOWN_END)
    if start < 0 or end < start:
        raise ValueError("custom_ids.md is missing generated section markers")
    end += len(MARKDOWN_END)
    return f"{document[:start]}{generated}{document[end:]}"


def expected_artifacts(root: Path, definition: ProtocolDefinition) -> dict[Path, str]:
    markdown_path = root / "protocol" / "custom_ids.md"
    markdown = replace_markdown_section(
        markdown_path.read_text(), render_markdown_section(definition)
    )
    return {
        root / "coordinator" / "src" / "e87canbus" / "protocol" / "generated.py": render_python(
            definition
        ),
        root / "devices" / "button-pad" / "include" / "can_ids.h": render_header(definition),
        root / "devices" / "servotronic-controller" / "include" / "can_ids.h": render_header(definition),
        markdown_path: markdown,
    }


def stale_artifacts(root: Path) -> tuple[Path, ...]:
    definition = load_definition(root / "protocol" / "custom.toml")
    return tuple(
        path
        for path, expected in expected_artifacts(root, definition).items()
        if not path.exists() or path.read_text() != expected
    )


def generate(root: Path) -> None:
    definition = load_definition(root / "protocol" / "custom.toml")
    for path, content in expected_artifacts(root, definition).items():
        path.write_text(content)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated artifacts differ.")
    args = parser.parse_args(argv)
    root = Path(__file__).resolve().parents[1]
    if not args.check:
        generate(root)
        return 0
    stale = stale_artifacts(root)
    for path in stale:
        print(f"out of date: {path.relative_to(root)}")
    return int(bool(stale))


if __name__ == "__main__":
    raise SystemExit(main())
