[env:micro]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino
lib_deps =
    EEPROM
    symlink://../../embedded-libs/isotp_transport
    https://github.com/coryjfowler/MCP_CAN_lib.git
    https://github.com/SimonCahill/isotp-c.git#b2fb084aadfed6e36a97a3e67282d2777fdad0d3
    adafruit/Adafruit seesaw Library
    adafruit/Adafruit NeoPixel
    adafruit/Adafruit BusIO
