[env:micro]
platform = atmelavr
board = micro
framework = arduino
lib_deps =
    EEPROM
    https://github.com/coryjfowler/MCP_CAN_lib.git
    https://github.com/SimonCahill/isotp-c.git#b2fb084aadfed6e36a97a3e67282d2777fdad0d3
