// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client"
import { client } from "./client.gen"
import type {
  ActivateSteeringCurveData,
  ActivateSteeringCurveErrors,
  ActivateSteeringCurveResponses,
  ActivateSteeringProfileData,
  ActivateSteeringProfileErrors,
  ActivateSteeringProfileResponses,
  AdjustManualAssistanceData,
  AdjustManualAssistanceErrors,
  AdjustManualAssistanceResponses,
  CheckLivenessData,
  CheckLivenessResponses,
  CheckReadinessData,
  CheckReadinessErrors,
  CheckReadinessResponses,
  ConnectSimulationDeviceData,
  ConnectSimulationDeviceErrors,
  ConnectSimulationDeviceResponses,
  CreateSteeringProfileData,
  CreateSteeringProfileErrors,
  CreateSteeringProfileResponses,
  DeleteSteeringProfileData,
  DeleteSteeringProfileErrors,
  DeleteSteeringProfileResponses,
  DisconnectSimulationDeviceData,
  DisconnectSimulationDeviceErrors,
  DisconnectSimulationDeviceResponses,
  GetApplicationSettingsData,
  GetApplicationSettingsErrors,
  GetApplicationSettingsResponses,
  GetRuntimeConfigurationData,
  GetRuntimeConfigurationResponses,
  GetSavedSteeringProfileData,
  GetSavedSteeringProfileErrors,
  GetSavedSteeringProfileResponses,
  GetSteeringProfileData,
  GetSteeringProfileErrors,
  GetSteeringProfileResponses,
  ListSteeringProfilesData,
  ListSteeringProfilesErrors,
  ListSteeringProfilesResponses,
  RebootSimulationDeviceData,
  RebootSimulationDeviceErrors,
  RebootSimulationDeviceResponses,
  ResetSimulationData,
  ResetSimulationErrors,
  ResetSimulationResponses,
  SetCoolantTemperatureData,
  SetCoolantTemperatureErrors,
  SetCoolantTemperatureResponses,
  SetEngineRpmData,
  SetEngineRpmErrors,
  SetEngineRpmResponses,
  SetManualAssistanceLevelData,
  SetManualAssistanceLevelErrors,
  SetManualAssistanceLevelResponses,
  SetMaximumAssistanceData,
  SetMaximumAssistanceErrors,
  SetMaximumAssistanceResponses,
  SetOilTemperatureData,
  SetOilTemperatureErrors,
  SetOilTemperatureResponses,
  SetSimulationDeviceProtocolVersionData,
  SetSimulationDeviceProtocolVersionErrors,
  SetSimulationDeviceProtocolVersionResponses,
  SetSimulationDeviceStatusCodeData,
  SetSimulationDeviceStatusCodeErrors,
  SetSimulationDeviceStatusCodeResponses,
  SetSteeringModeData,
  SetSteeringModeErrors,
  SetSteeringModeResponses,
  SetVehicleSpeedData,
  SetVehicleSpeedErrors,
  SetVehicleSpeedResponses,
  SilenceCoolantTemperatureData,
  SilenceCoolantTemperatureErrors,
  SilenceCoolantTemperatureResponses,
  SilenceEngineRpmData,
  SilenceEngineRpmErrors,
  SilenceEngineRpmResponses,
  SilenceOilTemperatureData,
  SilenceOilTemperatureErrors,
  SilenceOilTemperatureResponses,
  SilenceVehicleSpeedData,
  SilenceVehicleSpeedErrors,
  SilenceVehicleSpeedResponses,
  TapSimulationButtonData,
  TapSimulationButtonErrors,
  TapSimulationButtonResponses,
  UpdateApplicationSettingsData,
  UpdateApplicationSettingsErrors,
  UpdateApplicationSettingsResponses,
  UpdateSteeringProfileData,
  UpdateSteeringProfileErrors,
  UpdateSteeringProfileResponses,
} from "./types.gen"
import {
  zActivateSteeringCurveResponse,
  zActivateSteeringProfileResponse,
  zAdjustManualAssistanceResponse,
  zCheckLivenessResponse,
  zCheckReadinessResponse,
  zConnectSimulationDeviceResponse,
  zCreateSteeringProfileResponse,
  zDeleteSteeringProfileResponse,
  zDisconnectSimulationDeviceResponse,
  zGetApplicationSettingsResponse,
  zGetRuntimeConfigurationResponse,
  zGetSavedSteeringProfileResponse,
  zGetSteeringProfileResponse,
  zListSteeringProfilesResponse,
  zRebootSimulationDeviceResponse,
  zResetSimulationResponse,
  zSetCoolantTemperatureResponse,
  zSetEngineRpmResponse,
  zSetManualAssistanceLevelResponse,
  zSetMaximumAssistanceResponse,
  zSetOilTemperatureResponse,
  zSetSimulationDeviceProtocolVersionResponse,
  zSetSimulationDeviceStatusCodeResponse,
  zSetSteeringModeResponse,
  zSetVehicleSpeedResponse,
  zSilenceCoolantTemperatureResponse,
  zSilenceEngineRpmResponse,
  zSilenceOilTemperatureResponse,
  zSilenceVehicleSpeedResponse,
  zTapSimulationButtonResponse,
  zUpdateApplicationSettingsResponse,
  zUpdateSteeringProfileResponse,
} from "./zod.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Tap Button
 */
export const tapSimulationButton = <ThrowOnError extends boolean = true>(
  options: Options<TapSimulationButtonData, ThrowOnError>
): RequestResult<
  TapSimulationButtonResponses,
  TapSimulationButtonErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    TapSimulationButtonResponses,
    TapSimulationButtonErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zTapSimulationButtonResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/dev/simulation/devices/button-pad/buttons/{button_index}/tap",
    ...options,
  })

/**
 * Connect Device
 */
export const connectSimulationDevice = <ThrowOnError extends boolean = true>(
  options: Options<ConnectSimulationDeviceData, ThrowOnError>
): RequestResult<
  ConnectSimulationDeviceResponses,
  ConnectSimulationDeviceErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    ConnectSimulationDeviceResponses,
    ConnectSimulationDeviceErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zConnectSimulationDeviceResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/dev/simulation/devices/{role}/connect",
    ...options,
  })

/**
 * Disconnect Device
 */
export const disconnectSimulationDevice = <ThrowOnError extends boolean = true>(
  options: Options<DisconnectSimulationDeviceData, ThrowOnError>
): RequestResult<
  DisconnectSimulationDeviceResponses,
  DisconnectSimulationDeviceErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    DisconnectSimulationDeviceResponses,
    DisconnectSimulationDeviceErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zDisconnectSimulationDeviceResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/dev/simulation/devices/{role}/disconnect",
    ...options,
  })

/**
 * Set Device Protocol Version
 */
export const setSimulationDeviceProtocolVersion = <
  ThrowOnError extends boolean = true,
>(
  options: Options<SetSimulationDeviceProtocolVersionData, ThrowOnError>
): RequestResult<
  SetSimulationDeviceProtocolVersionResponses,
  SetSimulationDeviceProtocolVersionErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).put<
    SetSimulationDeviceProtocolVersionResponses,
    SetSimulationDeviceProtocolVersionErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zSetSimulationDeviceProtocolVersionResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/dev/simulation/devices/{role}/protocol-version",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Reboot Device
 */
export const rebootSimulationDevice = <ThrowOnError extends boolean = true>(
  options: Options<RebootSimulationDeviceData, ThrowOnError>
): RequestResult<
  RebootSimulationDeviceResponses,
  RebootSimulationDeviceErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    RebootSimulationDeviceResponses,
    RebootSimulationDeviceErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zRebootSimulationDeviceResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/dev/simulation/devices/{role}/reboot",
    ...options,
  })

/**
 * Set Device Status Code
 */
export const setSimulationDeviceStatusCode = <
  ThrowOnError extends boolean = true,
>(
  options: Options<SetSimulationDeviceStatusCodeData, ThrowOnError>
): RequestResult<
  SetSimulationDeviceStatusCodeResponses,
  SetSimulationDeviceStatusCodeErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).put<
    SetSimulationDeviceStatusCodeResponses,
    SetSimulationDeviceStatusCodeErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zSetSimulationDeviceStatusCodeResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/dev/simulation/devices/{role}/status-code",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Reset
 */
export const resetSimulation = <ThrowOnError extends boolean = true>(
  options?: Options<ResetSimulationData, ThrowOnError>
): RequestResult<
  ResetSimulationResponses,
  ResetSimulationErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).post<
    ResetSimulationResponses,
    ResetSimulationErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zResetSimulationResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/dev/simulation/reset",
    ...options,
  })

/**
 * Set Coolant Temperature
 */
export const setCoolantTemperature = <ThrowOnError extends boolean = true>(
  options: Options<SetCoolantTemperatureData, ThrowOnError>
): RequestResult<
  SetCoolantTemperatureResponses,
  SetCoolantTemperatureErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).put<
    SetCoolantTemperatureResponses,
    SetCoolantTemperatureErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zSetCoolantTemperatureResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/dev/simulation/vehicle/coolant-temperature",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Silence Coolant Temperature
 */
export const silenceCoolantTemperature = <ThrowOnError extends boolean = true>(
  options?: Options<SilenceCoolantTemperatureData, ThrowOnError>
): RequestResult<
  SilenceCoolantTemperatureResponses,
  SilenceCoolantTemperatureErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).post<
    SilenceCoolantTemperatureResponses,
    SilenceCoolantTemperatureErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zSilenceCoolantTemperatureResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/dev/simulation/vehicle/coolant-temperature/silence",
    ...options,
  })

/**
 * Set Oil Temperature
 */
export const setOilTemperature = <ThrowOnError extends boolean = true>(
  options: Options<SetOilTemperatureData, ThrowOnError>
): RequestResult<
  SetOilTemperatureResponses,
  SetOilTemperatureErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).put<
    SetOilTemperatureResponses,
    SetOilTemperatureErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zSetOilTemperatureResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/dev/simulation/vehicle/oil-temperature",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Silence Oil Temperature
 */
export const silenceOilTemperature = <ThrowOnError extends boolean = true>(
  options?: Options<SilenceOilTemperatureData, ThrowOnError>
): RequestResult<
  SilenceOilTemperatureResponses,
  SilenceOilTemperatureErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).post<
    SilenceOilTemperatureResponses,
    SilenceOilTemperatureErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zSilenceOilTemperatureResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/dev/simulation/vehicle/oil-temperature/silence",
    ...options,
  })

/**
 * Set Engine Rpm
 */
export const setEngineRpm = <ThrowOnError extends boolean = true>(
  options: Options<SetEngineRpmData, ThrowOnError>
): RequestResult<
  SetEngineRpmResponses,
  SetEngineRpmErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).put<
    SetEngineRpmResponses,
    SetEngineRpmErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zSetEngineRpmResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/dev/simulation/vehicle/rpm",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Silence Engine Rpm
 */
export const silenceEngineRpm = <ThrowOnError extends boolean = true>(
  options?: Options<SilenceEngineRpmData, ThrowOnError>
): RequestResult<
  SilenceEngineRpmResponses,
  SilenceEngineRpmErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).post<
    SilenceEngineRpmResponses,
    SilenceEngineRpmErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zSilenceEngineRpmResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/dev/simulation/vehicle/rpm/silence",
    ...options,
  })

/**
 * Set Vehicle Speed
 */
export const setVehicleSpeed = <ThrowOnError extends boolean = true>(
  options: Options<SetVehicleSpeedData, ThrowOnError>
): RequestResult<
  SetVehicleSpeedResponses,
  SetVehicleSpeedErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).put<
    SetVehicleSpeedResponses,
    SetVehicleSpeedErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zSetVehicleSpeedResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/dev/simulation/vehicle/speed",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Silence Vehicle Speed
 */
export const silenceVehicleSpeed = <ThrowOnError extends boolean = true>(
  options?: Options<SilenceVehicleSpeedData, ThrowOnError>
): RequestResult<
  SilenceVehicleSpeedResponses,
  SilenceVehicleSpeedErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).post<
    SilenceVehicleSpeedResponses,
    SilenceVehicleSpeedErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zSilenceVehicleSpeedResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/dev/simulation/vehicle/speed/silence",
    ...options,
  })

/**
 * Runtime Configuration
 */
export const getRuntimeConfiguration = <ThrowOnError extends boolean = true>(
  options?: Options<GetRuntimeConfigurationData, ThrowOnError>
): RequestResult<
  GetRuntimeConfigurationResponses,
  unknown,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    GetRuntimeConfigurationResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zGetRuntimeConfigurationResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/runtime",
    ...options,
  })

/**
 * Get Application Settings
 */
export const getApplicationSettings = <ThrowOnError extends boolean = true>(
  options?: Options<GetApplicationSettingsData, ThrowOnError>
): RequestResult<
  GetApplicationSettingsResponses,
  GetApplicationSettingsErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    GetApplicationSettingsResponses,
    GetApplicationSettingsErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zGetApplicationSettingsResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/settings",
    ...options,
  })

/**
 * Update Application Settings
 */
export const updateApplicationSettings = <ThrowOnError extends boolean = true>(
  options: Options<UpdateApplicationSettingsData, ThrowOnError>
): RequestResult<
  UpdateApplicationSettingsResponses,
  UpdateApplicationSettingsErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).put<
    UpdateApplicationSettingsResponses,
    UpdateApplicationSettingsErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zUpdateApplicationSettingsResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/settings",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Activate Steering Profile
 */
export const activateSteeringProfile = <ThrowOnError extends boolean = true>(
  options: Options<ActivateSteeringProfileData, ThrowOnError>
): RequestResult<
  ActivateSteeringProfileResponses,
  ActivateSteeringProfileErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    ActivateSteeringProfileResponses,
    ActivateSteeringProfileErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zActivateSteeringProfileResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/steering/activate-profile",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Activate Steering Curve
 */
export const activateSteeringCurve = <ThrowOnError extends boolean = true>(
  options: Options<ActivateSteeringCurveData, ThrowOnError>
): RequestResult<
  ActivateSteeringCurveResponses,
  ActivateSteeringCurveErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).put<
    ActivateSteeringCurveResponses,
    ActivateSteeringCurveErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zActivateSteeringCurveResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/steering/curve",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Adjust Manual Assistance
 */
export const adjustManualAssistance = <ThrowOnError extends boolean = true>(
  options: Options<AdjustManualAssistanceData, ThrowOnError>
): RequestResult<
  AdjustManualAssistanceResponses,
  AdjustManualAssistanceErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    AdjustManualAssistanceResponses,
    AdjustManualAssistanceErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zAdjustManualAssistanceResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/steering/manual-assistance-adjustment",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Set Manual Assistance Level
 */
export const setManualAssistanceLevel = <ThrowOnError extends boolean = true>(
  options: Options<SetManualAssistanceLevelData, ThrowOnError>
): RequestResult<
  SetManualAssistanceLevelResponses,
  SetManualAssistanceLevelErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).put<
    SetManualAssistanceLevelResponses,
    SetManualAssistanceLevelErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zSetManualAssistanceLevelResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/steering/manual-assistance-level",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Set Maximum Assistance
 */
export const setMaximumAssistance = <ThrowOnError extends boolean = true>(
  options: Options<SetMaximumAssistanceData, ThrowOnError>
): RequestResult<
  SetMaximumAssistanceResponses,
  SetMaximumAssistanceErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).put<
    SetMaximumAssistanceResponses,
    SetMaximumAssistanceErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zSetMaximumAssistanceResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/steering/maximum-assistance",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Set Steering Mode
 */
export const setSteeringMode = <ThrowOnError extends boolean = true>(
  options: Options<SetSteeringModeData, ThrowOnError>
): RequestResult<
  SetSteeringModeResponses,
  SetSteeringModeErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).put<
    SetSteeringModeResponses,
    SetSteeringModeErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zSetSteeringModeResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/steering/mode",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get Saved Steering Profile
 */
export const getSavedSteeringProfile = <ThrowOnError extends boolean = true>(
  options?: Options<GetSavedSteeringProfileData, ThrowOnError>
): RequestResult<
  GetSavedSteeringProfileResponses,
  GetSavedSteeringProfileErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    GetSavedSteeringProfileResponses,
    GetSavedSteeringProfileErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zGetSavedSteeringProfileResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/steering/profile",
    ...options,
  })

/**
 * List Steering Profiles
 */
export const listSteeringProfiles = <ThrowOnError extends boolean = true>(
  options?: Options<ListSteeringProfilesData, ThrowOnError>
): RequestResult<
  ListSteeringProfilesResponses,
  ListSteeringProfilesErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    ListSteeringProfilesResponses,
    ListSteeringProfilesErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zListSteeringProfilesResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/steering/profiles",
    ...options,
  })

/**
 * Create Steering Profile
 */
export const createSteeringProfile = <ThrowOnError extends boolean = true>(
  options: Options<CreateSteeringProfileData, ThrowOnError>
): RequestResult<
  CreateSteeringProfileResponses,
  CreateSteeringProfileErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    CreateSteeringProfileResponses,
    CreateSteeringProfileErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zCreateSteeringProfileResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/steering/profiles",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete Steering Profile
 */
export const deleteSteeringProfile = <ThrowOnError extends boolean = true>(
  options: Options<DeleteSteeringProfileData, ThrowOnError>
): RequestResult<
  DeleteSteeringProfileResponses,
  DeleteSteeringProfileErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).delete<
    DeleteSteeringProfileResponses,
    DeleteSteeringProfileErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zDeleteSteeringProfileResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/steering/profiles/{profile_id}",
    ...options,
  })

/**
 * Get Steering Profile
 */
export const getSteeringProfile = <ThrowOnError extends boolean = true>(
  options: Options<GetSteeringProfileData, ThrowOnError>
): RequestResult<
  GetSteeringProfileResponses,
  GetSteeringProfileErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).get<
    GetSteeringProfileResponses,
    GetSteeringProfileErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zGetSteeringProfileResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/steering/profiles/{profile_id}",
    ...options,
  })

/**
 * Update Steering Profile
 */
export const updateSteeringProfile = <ThrowOnError extends boolean = true>(
  options: Options<UpdateSteeringProfileData, ThrowOnError>
): RequestResult<
  UpdateSteeringProfileResponses,
  UpdateSteeringProfileErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).put<
    UpdateSteeringProfileResponses,
    UpdateSteeringProfileErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zUpdateSteeringProfileResponse.parseAsync(data),
    responseStyle: "data",
    url: "/api/steering/profiles/{profile_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Live
 */
export const checkLiveness = <ThrowOnError extends boolean = true>(
  options?: Options<CheckLivenessData, ThrowOnError>
): RequestResult<CheckLivenessResponses, unknown, ThrowOnError, "data"> =>
  (options?.client ?? client).get<
    CheckLivenessResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zCheckLivenessResponse.parseAsync(data),
    responseStyle: "data",
    url: "/health/live",
    ...options,
  })

/**
 * Ready
 */
export const checkReadiness = <ThrowOnError extends boolean = true>(
  options?: Options<CheckReadinessData, ThrowOnError>
): RequestResult<
  CheckReadinessResponses,
  CheckReadinessErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    CheckReadinessResponses,
    CheckReadinessErrors,
    ThrowOnError,
    "data"
  >({
    responseValidator: async (data) =>
      await zCheckReadinessResponse.parseAsync(data),
    responseStyle: "data",
    url: "/health/ready",
    ...options,
  })
