// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

/**
 * ActivateSteeringCurveRequest
 */
export type ActivateSteeringCurveRequest = {
  definition: SteeringCurveDefinitionRequest
}

/**
 * ActivateSteeringProfileRequest
 */
export type ActivateSteeringProfileRequest = {
  /**
   * Expected Revision
   */
  expected_revision: number
  /**
   * Profile Id
   */
  profile_id: string
}

/**
 * AdjustManualAssistanceRequest
 */
export type AdjustManualAssistanceRequest = {
  /**
   * Delta
   */
  delta: -1 | 1
}

/**
 * ApiProblemDetail
 */
export type ApiProblemDetail = {
  /**
   * Code
   */
  code:
    | "validation_error"
    | "settings_revision_conflict"
    | "settings_storage_error"
    | "profile_not_found"
    | "profile_revision_conflict"
    | "profile_name_conflict"
    | "profile_storage_error"
    | "runtime_queue_full"
    | "controller_unavailable"
    | "command_timeout"
    | "simulation_device_unavailable"
    | "controller_failed"
    | "feature_unavailable"
    | "controller_runtime_error"
  /**
   * Current Revision
   */
  current_revision?: number | null
  /**
   * Issues
   */
  issues?: Array<ValidationIssue> | null
  /**
   * Message
   */
  message: string
}

/**
 * ApiProblemResponse
 */
export type ApiProblemResponse = {
  error: ApiProblemDetail
}

/**
 * ApplicationSettingsResponse
 */
export type ApplicationSettingsResponse = {
  /**
   * Coolant Critical C
   */
  coolant_critical_c: number
  /**
   * Coolant Warning C
   */
  coolant_warning_c: number
  /**
   * Oil Critical C
   */
  oil_critical_c: number
  /**
   * Oil Warning C
   */
  oil_warning_c: number
  /**
   * Redline Rpm
   */
  redline_rpm: number
  /**
   * Revision
   */
  revision: number
  /**
   * Shift Stage 1 Rpm
   */
  shift_stage_1_rpm: number
  /**
   * Shift Stage 2 Rpm
   */
  shift_stage_2_rpm: number
  speed_unit: SpeedUnit
  temperature_unit: TemperatureUnit
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * CommandAcknowledgement
 */
export type CommandAcknowledgement = {
  /**
   * Accepted
   */
  accepted?: true
  /**
   * Boot Id
   */
  boot_id: string
  /**
   * Revision
   */
  revision: number
}

/**
 * CreateProfileRequest
 */
export type CreateProfileRequest = {
  definition: SteeringCurveDefinitionRequest
  /**
   * Name
   */
  name: string
}

/**
 * DeviceRole
 */
export type DeviceRole = "button_pad" | "servotronic_controller"

/**
 * EngineRpmRequest
 */
export type EngineRpmRequest = {
  /**
   * Rpm
   */
  rpm: number
}

/**
 * LivenessResponse
 */
export type LivenessResponse = {
  /**
   * Status
   */
  status?: "live"
}

/**
 * ReadinessResponse
 */
export type ReadinessResponse = {
  /**
   * Boot Id
   */
  boot_id: string
  /**
   * Status
   */
  status: "ready" | "not_ready"
}

/**
 * SetManualAssistanceLevelRequest
 */
export type SetManualAssistanceLevelRequest = {
  /**
   * Level
   */
  level: number
}

/**
 * SetMaximumAssistanceRequest
 */
export type SetMaximumAssistanceRequest = {
  /**
   * Enabled
   */
  enabled: boolean
}

/**
 * SetSteeringModeRequest
 */
export type SetSteeringModeRequest = {
  /**
   * Mode
   */
  mode: "auto" | "manual"
}

/**
 * SimulationCommandAcknowledgement
 */
export type SimulationCommandAcknowledgement = {
  /**
   * Accepted
   */
  accepted?: true
  /**
   * Boot Id
   */
  boot_id: string
}

/**
 * SimulationDeviceProtocolVersionRequest
 */
export type SimulationDeviceProtocolVersionRequest = {
  /**
   * Protocol Version
   */
  protocol_version: number
}

/**
 * SimulationDeviceStatusCodeRequest
 */
export type SimulationDeviceStatusCodeRequest = {
  /**
   * Status Code
   */
  status_code: number
}

/**
 * SpeedRequest
 */
export type SpeedRequest = {
  /**
   * Speed Kph
   */
  speed_kph: number
}

/**
 * SpeedUnit
 */
export type SpeedUnit = "mph" | "kmh"

/**
 * SteeringCurveDefinitionRequest
 */
export type SteeringCurveDefinitionRequest = {
  /**
   * Points
   */
  points: [
    SteeringCurvePointRequest,
    SteeringCurvePointRequest,
    SteeringCurvePointRequest,
    SteeringCurvePointRequest,
    SteeringCurvePointRequest,
    SteeringCurvePointRequest,
    SteeringCurvePointRequest,
    SteeringCurvePointRequest,
  ]
  /**
   * Schema Version
   */
  schema_version: 1
}

/**
 * SteeringCurveDefinitionResponse
 */
export type SteeringCurveDefinitionResponse = {
  /**
   * Points
   */
  points: [
    SteeringCurvePointResponse,
    SteeringCurvePointResponse,
    SteeringCurvePointResponse,
    SteeringCurvePointResponse,
    SteeringCurvePointResponse,
    SteeringCurvePointResponse,
    SteeringCurvePointResponse,
    SteeringCurvePointResponse,
  ]
  /**
   * Schema Version
   */
  schema_version: 1
}

/**
 * SteeringCurvePointRequest
 */
export type SteeringCurvePointRequest = {
  /**
   * Assistance Per Mille
   */
  assistance_per_mille: number
  /**
   * Speed Deci Kph
   */
  speed_deci_kph: number
}

/**
 * SteeringCurvePointResponse
 */
export type SteeringCurvePointResponse = {
  /**
   * Assistance Per Mille
   */
  assistance_per_mille: number
  /**
   * Speed Deci Kph
   */
  speed_deci_kph: number
}

/**
 * SteeringProfileResponse
 */
export type SteeringProfileResponse = {
  /**
   * Created At
   */
  created_at: string
  definition: SteeringCurveDefinitionResponse
  /**
   * Name
   */
  name: string
  /**
   * Profile Id
   */
  profile_id: string
  /**
   * Revision
   */
  revision: number
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * TemperatureRequest
 */
export type TemperatureRequest = {
  /**
   * Temperature C
   */
  temperature_c: number
}

/**
 * TemperatureUnit
 */
export type TemperatureUnit = "c" | "f"

/**
 * UpdateApplicationSettingsRequest
 */
export type UpdateApplicationSettingsRequest = {
  /**
   * Coolant Critical C
   */
  coolant_critical_c: number
  /**
   * Coolant Warning C
   */
  coolant_warning_c: number
  /**
   * Expected Revision
   */
  expected_revision: number
  /**
   * Oil Critical C
   */
  oil_critical_c: number
  /**
   * Oil Warning C
   */
  oil_warning_c: number
  /**
   * Redline Rpm
   */
  redline_rpm: number
  /**
   * Shift Stage 1 Rpm
   */
  shift_stage_1_rpm: number
  /**
   * Shift Stage 2 Rpm
   */
  shift_stage_2_rpm: number
  /**
   * Speed Unit
   */
  speed_unit: "mph" | "kmh"
  /**
   * Temperature Unit
   */
  temperature_unit: "c" | "f"
}

/**
 * UpdateProfileRequest
 */
export type UpdateProfileRequest = {
  definition: SteeringCurveDefinitionRequest
  /**
   * Expected Revision
   */
  expected_revision: number
  /**
   * Name
   */
  name: string
}

/**
 * ValidationIssue
 */
export type ValidationIssue = {
  /**
   * Location
   */
  location: Array<string | number>
  /**
   * Message
   */
  message: string
  /**
   * Type
   */
  type: string
}

export type TapSimulationButtonData = {
  body?: never
  path: {
    /**
     * Button Index
     */
    button_index: number
  }
  query?: never
  url: "/api/dev/simulation/devices/button-pad/buttons/{button_index}/tap"
}

export type TapSimulationButtonErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type TapSimulationButtonError =
  TapSimulationButtonErrors[keyof TapSimulationButtonErrors]

export type TapSimulationButtonResponses = {
  /**
   * Successful Response
   */
  200: SimulationCommandAcknowledgement
}

export type TapSimulationButtonResponse =
  TapSimulationButtonResponses[keyof TapSimulationButtonResponses]

export type ConnectSimulationDeviceData = {
  body?: never
  path: {
    role: DeviceRole
  }
  query?: never
  url: "/api/dev/simulation/devices/{role}/connect"
}

export type ConnectSimulationDeviceErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type ConnectSimulationDeviceError =
  ConnectSimulationDeviceErrors[keyof ConnectSimulationDeviceErrors]

export type ConnectSimulationDeviceResponses = {
  /**
   * Successful Response
   */
  200: SimulationCommandAcknowledgement
}

export type ConnectSimulationDeviceResponse =
  ConnectSimulationDeviceResponses[keyof ConnectSimulationDeviceResponses]

export type DisconnectSimulationDeviceData = {
  body?: never
  path: {
    role: DeviceRole
  }
  query?: never
  url: "/api/dev/simulation/devices/{role}/disconnect"
}

export type DisconnectSimulationDeviceErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type DisconnectSimulationDeviceError =
  DisconnectSimulationDeviceErrors[keyof DisconnectSimulationDeviceErrors]

export type DisconnectSimulationDeviceResponses = {
  /**
   * Successful Response
   */
  200: SimulationCommandAcknowledgement
}

export type DisconnectSimulationDeviceResponse =
  DisconnectSimulationDeviceResponses[keyof DisconnectSimulationDeviceResponses]

export type SetSimulationDeviceProtocolVersionData = {
  body: SimulationDeviceProtocolVersionRequest
  path: {
    role: DeviceRole
  }
  query?: never
  url: "/api/dev/simulation/devices/{role}/protocol-version"
}

export type SetSimulationDeviceProtocolVersionErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type SetSimulationDeviceProtocolVersionError =
  SetSimulationDeviceProtocolVersionErrors[keyof SetSimulationDeviceProtocolVersionErrors]

export type SetSimulationDeviceProtocolVersionResponses = {
  /**
   * Successful Response
   */
  200: SimulationCommandAcknowledgement
}

export type SetSimulationDeviceProtocolVersionResponse =
  SetSimulationDeviceProtocolVersionResponses[keyof SetSimulationDeviceProtocolVersionResponses]

export type RebootSimulationDeviceData = {
  body?: never
  path: {
    role: DeviceRole
  }
  query?: never
  url: "/api/dev/simulation/devices/{role}/reboot"
}

export type RebootSimulationDeviceErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type RebootSimulationDeviceError =
  RebootSimulationDeviceErrors[keyof RebootSimulationDeviceErrors]

export type RebootSimulationDeviceResponses = {
  /**
   * Successful Response
   */
  200: SimulationCommandAcknowledgement
}

export type RebootSimulationDeviceResponse =
  RebootSimulationDeviceResponses[keyof RebootSimulationDeviceResponses]

export type SetSimulationDeviceStatusCodeData = {
  body: SimulationDeviceStatusCodeRequest
  path: {
    role: DeviceRole
  }
  query?: never
  url: "/api/dev/simulation/devices/{role}/status-code"
}

export type SetSimulationDeviceStatusCodeErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type SetSimulationDeviceStatusCodeError =
  SetSimulationDeviceStatusCodeErrors[keyof SetSimulationDeviceStatusCodeErrors]

export type SetSimulationDeviceStatusCodeResponses = {
  /**
   * Successful Response
   */
  200: SimulationCommandAcknowledgement
}

export type SetSimulationDeviceStatusCodeResponse =
  SetSimulationDeviceStatusCodeResponses[keyof SetSimulationDeviceStatusCodeResponses]

export type ResetSimulationData = {
  body?: never
  path?: never
  query?: never
  url: "/api/dev/simulation/reset"
}

export type ResetSimulationErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type ResetSimulationError =
  ResetSimulationErrors[keyof ResetSimulationErrors]

export type ResetSimulationResponses = {
  /**
   * Successful Response
   */
  200: SimulationCommandAcknowledgement
}

export type ResetSimulationResponse =
  ResetSimulationResponses[keyof ResetSimulationResponses]

export type SetCoolantTemperatureData = {
  body: TemperatureRequest
  path?: never
  query?: never
  url: "/api/dev/simulation/vehicle/coolant-temperature"
}

export type SetCoolantTemperatureErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type SetCoolantTemperatureError =
  SetCoolantTemperatureErrors[keyof SetCoolantTemperatureErrors]

export type SetCoolantTemperatureResponses = {
  /**
   * Successful Response
   */
  200: SimulationCommandAcknowledgement
}

export type SetCoolantTemperatureResponse =
  SetCoolantTemperatureResponses[keyof SetCoolantTemperatureResponses]

export type SilenceCoolantTemperatureData = {
  body?: never
  path?: never
  query?: never
  url: "/api/dev/simulation/vehicle/coolant-temperature/silence"
}

export type SilenceCoolantTemperatureErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type SilenceCoolantTemperatureError =
  SilenceCoolantTemperatureErrors[keyof SilenceCoolantTemperatureErrors]

export type SilenceCoolantTemperatureResponses = {
  /**
   * Successful Response
   */
  200: SimulationCommandAcknowledgement
}

export type SilenceCoolantTemperatureResponse =
  SilenceCoolantTemperatureResponses[keyof SilenceCoolantTemperatureResponses]

export type SetOilTemperatureData = {
  body: TemperatureRequest
  path?: never
  query?: never
  url: "/api/dev/simulation/vehicle/oil-temperature"
}

export type SetOilTemperatureErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type SetOilTemperatureError =
  SetOilTemperatureErrors[keyof SetOilTemperatureErrors]

export type SetOilTemperatureResponses = {
  /**
   * Successful Response
   */
  200: SimulationCommandAcknowledgement
}

export type SetOilTemperatureResponse =
  SetOilTemperatureResponses[keyof SetOilTemperatureResponses]

export type SilenceOilTemperatureData = {
  body?: never
  path?: never
  query?: never
  url: "/api/dev/simulation/vehicle/oil-temperature/silence"
}

export type SilenceOilTemperatureErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type SilenceOilTemperatureError =
  SilenceOilTemperatureErrors[keyof SilenceOilTemperatureErrors]

export type SilenceOilTemperatureResponses = {
  /**
   * Successful Response
   */
  200: SimulationCommandAcknowledgement
}

export type SilenceOilTemperatureResponse =
  SilenceOilTemperatureResponses[keyof SilenceOilTemperatureResponses]

export type SetEngineRpmData = {
  body: EngineRpmRequest
  path?: never
  query?: never
  url: "/api/dev/simulation/vehicle/rpm"
}

export type SetEngineRpmErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type SetEngineRpmError = SetEngineRpmErrors[keyof SetEngineRpmErrors]

export type SetEngineRpmResponses = {
  /**
   * Successful Response
   */
  200: SimulationCommandAcknowledgement
}

export type SetEngineRpmResponse =
  SetEngineRpmResponses[keyof SetEngineRpmResponses]

export type SilenceEngineRpmData = {
  body?: never
  path?: never
  query?: never
  url: "/api/dev/simulation/vehicle/rpm/silence"
}

export type SilenceEngineRpmErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type SilenceEngineRpmError =
  SilenceEngineRpmErrors[keyof SilenceEngineRpmErrors]

export type SilenceEngineRpmResponses = {
  /**
   * Successful Response
   */
  200: SimulationCommandAcknowledgement
}

export type SilenceEngineRpmResponse =
  SilenceEngineRpmResponses[keyof SilenceEngineRpmResponses]

export type SetVehicleSpeedData = {
  body: SpeedRequest
  path?: never
  query?: never
  url: "/api/dev/simulation/vehicle/speed"
}

export type SetVehicleSpeedErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type SetVehicleSpeedError =
  SetVehicleSpeedErrors[keyof SetVehicleSpeedErrors]

export type SetVehicleSpeedResponses = {
  /**
   * Successful Response
   */
  200: SimulationCommandAcknowledgement
}

export type SetVehicleSpeedResponse =
  SetVehicleSpeedResponses[keyof SetVehicleSpeedResponses]

export type SilenceVehicleSpeedData = {
  body?: never
  path?: never
  query?: never
  url: "/api/dev/simulation/vehicle/speed/silence"
}

export type SilenceVehicleSpeedErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type SilenceVehicleSpeedError =
  SilenceVehicleSpeedErrors[keyof SilenceVehicleSpeedErrors]

export type SilenceVehicleSpeedResponses = {
  /**
   * Successful Response
   */
  200: SimulationCommandAcknowledgement
}

export type SilenceVehicleSpeedResponse =
  SilenceVehicleSpeedResponses[keyof SilenceVehicleSpeedResponses]

export type GetApplicationSettingsData = {
  body?: never
  path?: never
  query?: never
  url: "/api/settings"
}

export type GetApplicationSettingsErrors = {
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type GetApplicationSettingsError =
  GetApplicationSettingsErrors[keyof GetApplicationSettingsErrors]

export type GetApplicationSettingsResponses = {
  /**
   * Successful Response
   */
  200: ApplicationSettingsResponse
}

export type GetApplicationSettingsResponse =
  GetApplicationSettingsResponses[keyof GetApplicationSettingsResponses]

export type UpdateApplicationSettingsData = {
  body: UpdateApplicationSettingsRequest
  path?: never
  query?: never
  url: "/api/settings"
}

export type UpdateApplicationSettingsErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type UpdateApplicationSettingsError =
  UpdateApplicationSettingsErrors[keyof UpdateApplicationSettingsErrors]

export type UpdateApplicationSettingsResponses = {
  /**
   * Successful Response
   */
  200: ApplicationSettingsResponse
}

export type UpdateApplicationSettingsResponse =
  UpdateApplicationSettingsResponses[keyof UpdateApplicationSettingsResponses]

export type ActivateSteeringProfileData = {
  body: ActivateSteeringProfileRequest
  path?: never
  query?: never
  url: "/api/steering/activate-profile"
}

export type ActivateSteeringProfileErrors = {
  /**
   * Not Found
   */
  404: ApiProblemResponse
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type ActivateSteeringProfileError =
  ActivateSteeringProfileErrors[keyof ActivateSteeringProfileErrors]

export type ActivateSteeringProfileResponses = {
  /**
   * Successful Response
   */
  200: CommandAcknowledgement
}

export type ActivateSteeringProfileResponse =
  ActivateSteeringProfileResponses[keyof ActivateSteeringProfileResponses]

export type ActivateSteeringCurveData = {
  body: ActivateSteeringCurveRequest
  path?: never
  query?: never
  url: "/api/steering/curve"
}

export type ActivateSteeringCurveErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type ActivateSteeringCurveError =
  ActivateSteeringCurveErrors[keyof ActivateSteeringCurveErrors]

export type ActivateSteeringCurveResponses = {
  /**
   * Successful Response
   */
  200: CommandAcknowledgement
}

export type ActivateSteeringCurveResponse =
  ActivateSteeringCurveResponses[keyof ActivateSteeringCurveResponses]

export type AdjustManualAssistanceData = {
  body: AdjustManualAssistanceRequest
  path?: never
  query?: never
  url: "/api/steering/manual-assistance-adjustment"
}

export type AdjustManualAssistanceErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type AdjustManualAssistanceError =
  AdjustManualAssistanceErrors[keyof AdjustManualAssistanceErrors]

export type AdjustManualAssistanceResponses = {
  /**
   * Successful Response
   */
  200: CommandAcknowledgement
}

export type AdjustManualAssistanceResponse =
  AdjustManualAssistanceResponses[keyof AdjustManualAssistanceResponses]

export type SetManualAssistanceLevelData = {
  body: SetManualAssistanceLevelRequest
  path?: never
  query?: never
  url: "/api/steering/manual-assistance-level"
}

export type SetManualAssistanceLevelErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type SetManualAssistanceLevelError =
  SetManualAssistanceLevelErrors[keyof SetManualAssistanceLevelErrors]

export type SetManualAssistanceLevelResponses = {
  /**
   * Successful Response
   */
  200: CommandAcknowledgement
}

export type SetManualAssistanceLevelResponse =
  SetManualAssistanceLevelResponses[keyof SetManualAssistanceLevelResponses]

export type SetMaximumAssistanceData = {
  body: SetMaximumAssistanceRequest
  path?: never
  query?: never
  url: "/api/steering/maximum-assistance"
}

export type SetMaximumAssistanceErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type SetMaximumAssistanceError =
  SetMaximumAssistanceErrors[keyof SetMaximumAssistanceErrors]

export type SetMaximumAssistanceResponses = {
  /**
   * Successful Response
   */
  200: CommandAcknowledgement
}

export type SetMaximumAssistanceResponse =
  SetMaximumAssistanceResponses[keyof SetMaximumAssistanceResponses]

export type SetSteeringModeData = {
  body: SetSteeringModeRequest
  path?: never
  query?: never
  url: "/api/steering/mode"
}

export type SetSteeringModeErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type SetSteeringModeError =
  SetSteeringModeErrors[keyof SetSteeringModeErrors]

export type SetSteeringModeResponses = {
  /**
   * Successful Response
   */
  200: CommandAcknowledgement
}

export type SetSteeringModeResponse =
  SetSteeringModeResponses[keyof SetSteeringModeResponses]

export type GetSavedSteeringProfileData = {
  body?: never
  path?: never
  query?: never
  url: "/api/steering/profile"
}

export type GetSavedSteeringProfileErrors = {
  /**
   * Not Found
   */
  404: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type GetSavedSteeringProfileError =
  GetSavedSteeringProfileErrors[keyof GetSavedSteeringProfileErrors]

export type GetSavedSteeringProfileResponses = {
  /**
   * Successful Response
   */
  200: SteeringProfileResponse
}

export type GetSavedSteeringProfileResponse =
  GetSavedSteeringProfileResponses[keyof GetSavedSteeringProfileResponses]

export type ListSteeringProfilesData = {
  body?: never
  path?: never
  query?: never
  url: "/api/steering/profiles"
}

export type ListSteeringProfilesErrors = {
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type ListSteeringProfilesError =
  ListSteeringProfilesErrors[keyof ListSteeringProfilesErrors]

export type ListSteeringProfilesResponses = {
  /**
   * Response Liststeeringprofiles
   *
   * Successful Response
   */
  200: Array<SteeringProfileResponse>
}

export type ListSteeringProfilesResponse =
  ListSteeringProfilesResponses[keyof ListSteeringProfilesResponses]

export type CreateSteeringProfileData = {
  body: CreateProfileRequest
  path?: never
  query?: never
  url: "/api/steering/profiles"
}

export type CreateSteeringProfileErrors = {
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type CreateSteeringProfileError =
  CreateSteeringProfileErrors[keyof CreateSteeringProfileErrors]

export type CreateSteeringProfileResponses = {
  /**
   * Successful Response
   */
  201: SteeringProfileResponse
}

export type CreateSteeringProfileResponse =
  CreateSteeringProfileResponses[keyof CreateSteeringProfileResponses]

export type DeleteSteeringProfileData = {
  body?: never
  path: {
    /**
     * Profile Id
     */
    profile_id: string
  }
  query: {
    /**
     * Expected Revision
     */
    expected_revision: number
  }
  url: "/api/steering/profiles/{profile_id}"
}

export type DeleteSteeringProfileErrors = {
  /**
   * Not Found
   */
  404: ApiProblemResponse
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type DeleteSteeringProfileError =
  DeleteSteeringProfileErrors[keyof DeleteSteeringProfileErrors]

export type DeleteSteeringProfileResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteSteeringProfileResponse =
  DeleteSteeringProfileResponses[keyof DeleteSteeringProfileResponses]

export type GetSteeringProfileData = {
  body?: never
  path: {
    /**
     * Profile Id
     */
    profile_id: string
  }
  query?: never
  url: "/api/steering/profiles/{profile_id}"
}

export type GetSteeringProfileErrors = {
  /**
   * Not Found
   */
  404: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type GetSteeringProfileError =
  GetSteeringProfileErrors[keyof GetSteeringProfileErrors]

export type GetSteeringProfileResponses = {
  /**
   * Successful Response
   */
  200: SteeringProfileResponse
}

export type GetSteeringProfileResponse =
  GetSteeringProfileResponses[keyof GetSteeringProfileResponses]

export type UpdateSteeringProfileData = {
  body: UpdateProfileRequest
  path: {
    /**
     * Profile Id
     */
    profile_id: string
  }
  query?: never
  url: "/api/steering/profiles/{profile_id}"
}

export type UpdateSteeringProfileErrors = {
  /**
   * Not Found
   */
  404: ApiProblemResponse
  /**
   * Conflict
   */
  409: ApiProblemResponse
  /**
   * Unprocessable Entity
   */
  422: ApiProblemResponse
  /**
   * Service Unavailable
   */
  503: ApiProblemResponse
}

export type UpdateSteeringProfileError =
  UpdateSteeringProfileErrors[keyof UpdateSteeringProfileErrors]

export type UpdateSteeringProfileResponses = {
  /**
   * Successful Response
   */
  200: SteeringProfileResponse
}

export type UpdateSteeringProfileResponse =
  UpdateSteeringProfileResponses[keyof UpdateSteeringProfileResponses]

export type CheckLivenessData = {
  body?: never
  path?: never
  query?: never
  url: "/health/live"
}

export type CheckLivenessResponses = {
  /**
   * Successful Response
   */
  200: LivenessResponse
}

export type CheckLivenessResponse =
  CheckLivenessResponses[keyof CheckLivenessResponses]

export type CheckReadinessData = {
  body?: never
  path?: never
  query?: never
  url: "/health/ready"
}

export type CheckReadinessErrors = {
  /**
   * Service Unavailable
   */
  503: ReadinessResponse
}

export type CheckReadinessError =
  CheckReadinessErrors[keyof CheckReadinessErrors]

export type CheckReadinessResponses = {
  /**
   * Successful Response
   */
  200: ReadinessResponse
}

export type CheckReadinessResponse =
  CheckReadinessResponses[keyof CheckReadinessResponses]
