// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod"

/**
 * ActivateSteeringProfileRequest
 */
export const zActivateSteeringProfileRequest = z.object({
  expected_revision: z.int().gte(1),
  profile_id: z
    .string()
    .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/),
})

/**
 * CommandAcknowledgement
 */
export const zCommandAcknowledgement = z.object({
  accepted: z.literal(true).optional().default(true),
  boot_id: z.string(),
  revision: z.int().gte(1),
})

/**
 * DeviceRole
 */
export const zDeviceRole = z.enum(["button_pad", "servotronic_controller"])

/**
 * EngineRpmRequest
 */
export const zEngineRpmRequest = z.object({
  rpm: z.int().gte(0).lte(12000),
})

/**
 * LivenessResponse
 */
export const zLivenessResponse = z.object({
  status: z.literal("live").optional().default("live"),
})

/**
 * ReadinessResponse
 */
export const zReadinessResponse = z.object({
  boot_id: z.string().min(1),
  status: z.enum(["ready", "not_ready"]),
})

/**
 * SetMaximumAssistanceRequest
 */
export const zSetMaximumAssistanceRequest = z.object({
  enabled: z.boolean(),
})

/**
 * SetSteeringModeRequest
 */
export const zSetSteeringModeRequest = z.object({
  manual_level: z.int().gte(0).nullish(),
  mode: z.enum(["auto", "manual"]),
})

/**
 * SimulationCommandAcknowledgement
 */
export const zSimulationCommandAcknowledgement = z.object({
  accepted: z.literal(true).optional().default(true),
  boot_id: z.string(),
})

/**
 * SimulationDeviceProtocolVersionRequest
 */
export const zSimulationDeviceProtocolVersionRequest = z.object({
  protocol_version: z.int().gte(0).lte(255),
})

/**
 * SimulationDeviceStatusCodeRequest
 */
export const zSimulationDeviceStatusCodeRequest = z.object({
  status_code: z.int().gte(0).lte(255),
})

/**
 * SpeedRequest
 */
export const zSpeedRequest = z.object({
  speed_kph: z.number().gte(0).lte(300),
})

/**
 * SpeedUnit
 */
export const zSpeedUnit = z.enum(["mph", "kmh"])

/**
 * SteeringCurvePointRequest
 */
export const zSteeringCurvePointRequest = z.object({
  assistance_per_mille: z.int().gte(0).lte(1000),
  speed_deci_kph: z.int().gte(0),
})

/**
 * SteeringCurveDefinitionRequest
 */
export const zSteeringCurveDefinitionRequest = z.object({
  points: z.tuple([
    zSteeringCurvePointRequest,
    zSteeringCurvePointRequest,
    zSteeringCurvePointRequest,
    zSteeringCurvePointRequest,
    zSteeringCurvePointRequest,
    zSteeringCurvePointRequest,
    zSteeringCurvePointRequest,
    zSteeringCurvePointRequest,
  ]),
  schema_version: z.literal(1),
})

/**
 * ActivateSteeringCurveRequest
 */
export const zActivateSteeringCurveRequest = z.object({
  definition: zSteeringCurveDefinitionRequest,
})

/**
 * CreateProfileRequest
 */
export const zCreateProfileRequest = z.object({
  definition: zSteeringCurveDefinitionRequest,
  name: z.string().min(1).max(100),
})

/**
 * SteeringCurvePointResponse
 */
export const zSteeringCurvePointResponse = z.object({
  assistance_per_mille: z.int().gte(0).lte(1000),
  speed_deci_kph: z.int().gte(0),
})

/**
 * SteeringCurveDefinitionResponse
 */
export const zSteeringCurveDefinitionResponse = z.object({
  points: z.tuple([
    zSteeringCurvePointResponse,
    zSteeringCurvePointResponse,
    zSteeringCurvePointResponse,
    zSteeringCurvePointResponse,
    zSteeringCurvePointResponse,
    zSteeringCurvePointResponse,
    zSteeringCurvePointResponse,
    zSteeringCurvePointResponse,
  ]),
  schema_version: z.literal(1),
})

/**
 * SteeringProfileResponse
 */
export const zSteeringProfileResponse = z.object({
  created_at: z.string(),
  definition: zSteeringCurveDefinitionResponse,
  name: z.string().min(1).max(100),
  profile_id: z
    .string()
    .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/),
  revision: z.int().gte(1),
  updated_at: z.string(),
})

/**
 * TemperatureRequest
 */
export const zTemperatureRequest = z.object({
  temperature_c: z.number().gte(-40).lte(250),
})

/**
 * TemperatureUnit
 */
export const zTemperatureUnit = z.enum(["c", "f"])

/**
 * ApplicationSettingsResponse
 */
export const zApplicationSettingsResponse = z.object({
  coolant_critical_c: z.number(),
  coolant_warning_c: z.number(),
  oil_critical_c: z.number(),
  oil_warning_c: z.number(),
  redline_rpm: z.int(),
  revision: z.int().gte(1),
  shift_stage_1_rpm: z.int(),
  shift_stage_2_rpm: z.int(),
  speed_unit: zSpeedUnit,
  temperature_unit: zTemperatureUnit,
  updated_at: z.string(),
})

/**
 * UpdateApplicationSettingsRequest
 */
export const zUpdateApplicationSettingsRequest = z.object({
  coolant_critical_c: z.number().gte(-40).lte(250),
  coolant_warning_c: z.number().gte(-40).lte(250),
  expected_revision: z.int().gte(1),
  oil_critical_c: z.number().gte(-40).lte(250),
  oil_warning_c: z.number().gte(-40).lte(250),
  redline_rpm: z.int().gte(1000).lte(12000),
  shift_stage_1_rpm: z.int().gte(1000).lte(12000),
  shift_stage_2_rpm: z.int().gte(1000).lte(12000),
  speed_unit: z.enum(["mph", "kmh"]),
  temperature_unit: z.enum(["c", "f"]),
})

/**
 * UpdateProfileRequest
 */
export const zUpdateProfileRequest = z.object({
  definition: zSteeringCurveDefinitionRequest,
  expected_revision: z.int().gte(1),
  name: z.string().min(1).max(100),
})

/**
 * ValidationIssue
 */
export const zValidationIssue = z.object({
  location: z.array(z.union([z.string(), z.int()])),
  message: z.string(),
  type: z.string(),
})

/**
 * ApiProblemDetail
 */
export const zApiProblemDetail = z.object({
  code: z.enum([
    "validation_error",
    "settings_revision_conflict",
    "settings_storage_error",
    "profile_not_found",
    "profile_revision_conflict",
    "profile_name_conflict",
    "profile_storage_error",
    "runtime_queue_full",
    "controller_unavailable",
    "command_timeout",
    "simulation_device_unavailable",
    "controller_failed",
    "feature_unavailable",
    "controller_runtime_error",
  ]),
  current_revision: z.int().nullish(),
  issues: z.array(zValidationIssue).nullish(),
  message: z.string(),
})

/**
 * ApiProblemResponse
 */
export const zApiProblemResponse = z.object({
  error: zApiProblemDetail,
})

export const zActivateSteeringProfileBody = zActivateSteeringProfileRequest

/**
 * Successful Response
 */
export const zActivateSteeringProfileResponse = zCommandAcknowledgement

export const zSetMaximumAssistanceBody = zSetMaximumAssistanceRequest

/**
 * Successful Response
 */
export const zSetMaximumAssistanceResponse = zCommandAcknowledgement

export const zActivateSteeringCurveBody = zActivateSteeringCurveRequest

/**
 * Successful Response
 */
export const zActivateSteeringCurveResponse = zCommandAcknowledgement

export const zSetSteeringModeBody = zSetSteeringModeRequest

/**
 * Successful Response
 */
export const zSetSteeringModeResponse = zCommandAcknowledgement

export const zTapSimulationButtonPath = z.object({
  button_index: z.int().gte(0).lt(16),
})

/**
 * Successful Response
 */
export const zTapSimulationButtonResponse = zSimulationCommandAcknowledgement

export const zConnectSimulationDevicePath = z.object({
  role: zDeviceRole,
})

/**
 * Successful Response
 */
export const zConnectSimulationDeviceResponse =
  zSimulationCommandAcknowledgement

export const zDisconnectSimulationDevicePath = z.object({
  role: zDeviceRole,
})

/**
 * Successful Response
 */
export const zDisconnectSimulationDeviceResponse =
  zSimulationCommandAcknowledgement

export const zSetSimulationDeviceProtocolVersionBody =
  zSimulationDeviceProtocolVersionRequest

export const zSetSimulationDeviceProtocolVersionPath = z.object({
  role: zDeviceRole,
})

/**
 * Successful Response
 */
export const zSetSimulationDeviceProtocolVersionResponse =
  zSimulationCommandAcknowledgement

export const zRebootSimulationDevicePath = z.object({
  role: zDeviceRole,
})

/**
 * Successful Response
 */
export const zRebootSimulationDeviceResponse = zSimulationCommandAcknowledgement

export const zSetSimulationDeviceStatusCodeBody =
  zSimulationDeviceStatusCodeRequest

export const zSetSimulationDeviceStatusCodePath = z.object({
  role: zDeviceRole,
})

/**
 * Successful Response
 */
export const zSetSimulationDeviceStatusCodeResponse =
  zSimulationCommandAcknowledgement

/**
 * Successful Response
 */
export const zResetSimulationResponse = zSimulationCommandAcknowledgement

export const zSetCoolantTemperatureBody = zTemperatureRequest

/**
 * Successful Response
 */
export const zSetCoolantTemperatureResponse = zSimulationCommandAcknowledgement

/**
 * Successful Response
 */
export const zSilenceCoolantTemperatureResponse =
  zSimulationCommandAcknowledgement

export const zSetOilTemperatureBody = zTemperatureRequest

/**
 * Successful Response
 */
export const zSetOilTemperatureResponse = zSimulationCommandAcknowledgement

/**
 * Successful Response
 */
export const zSilenceOilTemperatureResponse = zSimulationCommandAcknowledgement

export const zSetEngineRpmBody = zEngineRpmRequest

/**
 * Successful Response
 */
export const zSetEngineRpmResponse = zSimulationCommandAcknowledgement

/**
 * Successful Response
 */
export const zSilenceEngineRpmResponse = zSimulationCommandAcknowledgement

export const zSetVehicleSpeedBody = zSpeedRequest

/**
 * Successful Response
 */
export const zSetVehicleSpeedResponse = zSimulationCommandAcknowledgement

/**
 * Successful Response
 */
export const zSilenceVehicleSpeedResponse = zSimulationCommandAcknowledgement

/**
 * Successful Response
 */
export const zGetApplicationSettingsResponse = zApplicationSettingsResponse

export const zUpdateApplicationSettingsBody = zUpdateApplicationSettingsRequest

/**
 * Successful Response
 */
export const zUpdateApplicationSettingsResponse = zApplicationSettingsResponse

/**
 * Successful Response
 */
export const zGetSavedSteeringProfileResponse = zSteeringProfileResponse

/**
 * Response Liststeeringprofiles
 *
 * Successful Response
 */
export const zListSteeringProfilesResponse = z.array(zSteeringProfileResponse)

export const zCreateSteeringProfileBody = zCreateProfileRequest

/**
 * Successful Response
 */
export const zCreateSteeringProfileResponse = zSteeringProfileResponse

export const zDeleteSteeringProfilePath = z.object({
  profile_id: z
    .string()
    .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/),
})

export const zDeleteSteeringProfileQuery = z.object({
  expected_revision: z.int().gte(1),
})

/**
 * Successful Response
 */
export const zDeleteSteeringProfileResponse = z.void()

export const zGetSteeringProfilePath = z.object({
  profile_id: z
    .string()
    .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/),
})

/**
 * Successful Response
 */
export const zGetSteeringProfileResponse = zSteeringProfileResponse

export const zUpdateSteeringProfileBody = zUpdateProfileRequest

export const zUpdateSteeringProfilePath = z.object({
  profile_id: z
    .string()
    .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/),
})

/**
 * Successful Response
 */
export const zUpdateSteeringProfileResponse = zSteeringProfileResponse

/**
 * Successful Response
 */
export const zCheckLivenessResponse = zLivenessResponse

/**
 * Successful Response
 */
export const zCheckReadinessResponse = zReadinessResponse
