/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SteeringIndexRouteImport } from './routes/steering/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ButtonsIndexRouteImport } from './routes/buttons/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SteeringIndexRoute = SteeringIndexRouteImport.update({
  id: '/steering/',
  path: '/steering/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonsIndexRoute = ButtonsIndexRouteImport.update({
  id: '/buttons/',
  path: '/buttons/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buttons/': typeof ButtonsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/steering/': typeof SteeringIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buttons': typeof ButtonsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/steering': typeof SteeringIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buttons/': typeof ButtonsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/steering/': typeof SteeringIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/buttons/' | '/settings/' | '/steering/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/buttons' | '/settings' | '/steering'
  id: '__root__' | '/' | '/buttons/' | '/settings/' | '/steering/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ButtonsIndexRoute: typeof ButtonsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SteeringIndexRoute: typeof SteeringIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steering/': {
      id: '/steering/'
      path: '/steering'
      fullPath: '/steering/'
      preLoaderRoute: typeof SteeringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buttons/': {
      id: '/buttons/'
      path: '/buttons'
      fullPath: '/buttons/'
      preLoaderRoute: typeof ButtonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ButtonsIndexRoute: ButtonsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SteeringIndexRoute: SteeringIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
