[Unit]
Requires=dev-ttyAMA3.device
After=dev-ttyAMA3.device
ConditionPathExists=!/var/lib/e87canbus-provisioning/unprovisioned
ConditionFileIsExecutable=/opt/e87canbus/current/venv/bin/e87canbus

[Service]
ExecStart=
ExecStart=/opt/e87canbus/current/venv/bin/e87canbus run --profile ${E87CANBUS_PROFILE} --host 127.0.0.1 --port ${E87CANBUS_PORT} --profile-database ${E87CANBUS_DATABASE} --frontend-directory ${E87CANBUS_FRONTEND} --cors-origin ${E87CANBUS_CONSOLE_ORIGIN}
